org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
neo_version_range=[21.1.0,)
loader_version_range=[1,)

mod_id=zerog_tweaks
mod_name=ZeroG Tweaks
mod_license=All Rights Reserved
mod_version=1.0.7-dev
mod_group_id=net.zerog.tweaks
mod_authors=Jake M.
mod_description=Draconic-style Alveary multiblock expansion: animated cores, emissive circuitry, tiered controllers, and genetic engineering.

geckolib_version=4.9.3
