"""Spawn eggs for the 28 ZeroG mobs and the 10 Shattered Skies creatures.
Writes ZGSpawnEggs.java (items), client/ZGItemColors.java (egg colours), item models and lang.
Eggs resolve their entity type by id at use time, so they work as soon as the entity is registered."""
import json, re, glob, os

REPO = '/home/claude/zerog-tweaks'
A = f'{REPO}/src/main/resources/assets/zerog_tweaks'
J = f'{REPO}/src/main/java/net/zerog/tweaks'

# ZeroG mobs: colours from the design-bundle egg table (mob palette base, spots)
zg = re.findall(r'egg\("(\w+)", ZGEntities\.\w+, 0x([0-9A-Fa-f]{6}), 0x([0-9A-Fa-f]{6})\)',
                open(f'{REPO}/docs/zero-g-tweaks-bundle/java/item/ZGSpawnEggs.java').read())
LANG = json.load(open(f'{A}/lang/en_us.json'))
EGGS = []  # (key, name, base, spots, entity ids to try)
for k, b, s in zg:
    name = LANG[f'item.zerog_tweaks.{k}_spawn_egg'].replace(' Spawn Egg', '')
    EGGS.append((k, name, int(b, 16), int(s, 16), [f'zerog_tweaks:{k}']))

# Shattered Skies creatures: base = the colour covering the most model volume, spots = the violet splinter (family mark)
for f in sorted(glob.glob(f'{REPO}/docs/shattered-skies/models/*.json')):
    j = json.load(open(f))
    if 'boxes' not in j: continue
    vol = {}
    for bx in j['boxes']:
        v = 1
        for a, c in zip(bx['from'], bx['to']): v *= abs(c - a)
        vol[bx['color']] = vol.get(bx['color'], 0) + v
    main = max(vol, key=vol.get)
    base = j['palette'][main]; spots = j['palette'].get('splinter', '#c9a8ff')
    if j['id'] == 'splinter_wisp': base, spots = j['palette']['splinter'], j['palette'].get('glow', '#ffffff')
    EGGS.append((j['id'], j['name'], int(base[1:], 16), int(spots[1:], 16), [f'shatteredskies:{j["id"]}', f'zerog_tweaks:{j["id"]}']))

EGGS.sort(key=lambda e: e[0])  # vanilla lists spawn eggs alphabetically
for k, name, b, s, ids in EGGS:
    json.dump({'parent': 'minecraft:item/template_spawn_egg'}, open(f'{A}/models/item/{k}_spawn_egg.json', 'w'), indent=2)
    LANG[f'item.zerog_tweaks.{k}_spawn_egg'] = f'{name} Spawn Egg'
LANG['item.zerog_tweaks.spawn_egg.not_ready'] = '%s: this mob is not in the game yet'
LANG['itemGroup.zerog_tweaks.spawn_eggs'] = 'ZeroG: Spawn Eggs'
open(f'{A}/lang/en_us.json', 'w').write(json.dumps(LANG, indent=2, ensure_ascii=False) + '\n')

rows = '\n'.join(f'    public static final DeferredItem<ZGSpawnEggItem> {k.upper()} = egg("{k}", 0x{b:06X}, 0x{s:06X}, '
                 + ', '.join(f'"{i}"' for i in ids) + ');' for k, _, b, s, ids in EGGS)
open(f'{J}/registry/ZGSpawnEggs.java', 'w').write(f'''package net.zerog.tweaks.registry;

import java.util.ArrayList;
import java.util.List;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;

/**
 * GENERATED by docs/zero-g-tweaks-bundle/generators/spawn_eggs.py; do not edit by hand.
 * Spawn eggs for the {len(zg)} ZeroG mobs and the {len(EGGS) - len(zg)} Shattered Skies creatures (ids "<mob>_spawn_egg").
 * Each egg looks up its entity type by id when used (see {{@link ZGSpawnEggItem}}), so it starts
 * working the moment that entity is registered; until then it shows a "not in the game yet" message.
 * Shattered Skies eggs try "shatteredskies:<id>" first, then "zerog_tweaks:<id>".
 */
public final class ZGSpawnEggs {{
    private ZGSpawnEggs() {{}}

    public static final List<DeferredItem<ZGSpawnEggItem>> ALL = new ArrayList<>();

    private static DeferredItem<ZGSpawnEggItem> egg(String key, int base, int spots, String... entityIds) {{
        DeferredItem<ZGSpawnEggItem> item = ItemInit.ITEMS.register(key + "_spawn_egg",
                () -> new ZGSpawnEggItem(base, spots, entityIds, new Item.Properties()));
        ALL.add(item);
        return item;
    }}

{rows}

    /** Called from ItemInit so the static fields above are initialised before the register is frozen. */
    static void init() {{}}
}}
''')
open(f'{REPO}/docs/zero-g-tweaks-bundle/data/spawn_eggs.csv', 'w').write(
    'egg,name,base,spots,entity_ids\n' + '\n'.join(f'zerog_tweaks:{k}_spawn_egg,{n},#{b:06X},#{s:06X},{" ".join(i)}' for k, n, b, s, i in EGGS) + '\n')
print(len(EGGS), 'eggs')
