package net.zerog.tweaks.genetics;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.energy.IEnergyStorage;
import net.neoforged.neoforge.items.IItemHandler;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;

/** Physical ports bind only to one currently valid, loaded same-tier5³ controller. */
public final class AlvearyPorts {
    public static boolean itemPort(String id){return id.matches("tier[1-7]_(input_hatch|output_hatch|frame_loader)");}
    public static BlockEntity controller(ServerLevel level,BlockPos port){if(!level.hasChunkAt(port))return null;var state=level.getBlockState(port);var key=BuiltInRegistries.BLOCK.getKey(state.getBlock());var id=key.getPath();boolean nativePart=key.getNamespace().equals("aeroapiary")&&id.matches("tier[1-7]_.*");if(!nativePart&&AlvearyFormation.role(state)==AlvearyFormation.Role.NONE)return null;int tier=nativePart?id.charAt(4)-'0':0;BlockEntity found=null;
        for(int x=-4;x<=4;x++)for(int y=-4;y<=1;y++)for(int z=-4;z<=4;z++){var pos=port.offset(x,y,z);if(!level.hasChunkAt(pos))continue;var candidate=level.getBlockEntity(pos);String name=GeneticsRuntime.id(candidate);int candidateTier=AlvearyRuntime.tier(candidate);if(candidateTier==0||name.equals("zero_g_hive")||tier!=0&&tier!=candidateTier)continue;try{candidate.getClass().getMethod("updateFormation").invoke(candidate);}catch(ReflectiveOperationException ex){continue;}if(!AlvearyRuntime.formed(candidate)||!inside(candidate,port))continue;if(found!=null&&found!=candidate)return null;found=candidate;}return found;
    }
    /** The horizontal corner chunks cover every block read by the addon's 5³ validator. */
    public static boolean footprintLoaded(ServerLevel level,BlockPos anchor){for(int x=0;x<=4;x+=4)for(int z=0;z<=4;z+=4)if(!level.hasChunkAt(anchor.offset(-x,0,-z)))return false;return true;}
    /** Unlike controller(), this distinguishes ambiguous formed ownership from no formed shell. */
    public static boolean hasFormedController(ServerLevel level,BlockPos port){if(!level.hasChunkAt(port))return false;for(int x=-4;x<=4;x++)for(int y=-4;y<=1;y++)for(int z=-4;z<=4;z++){var pos=port.offset(x,y,z);if(!level.hasChunkAt(pos))continue;var be=level.getBlockEntity(pos);int tier=AlvearyRuntime.tier(be);if(tier>0&&!GeneticsRuntime.id(be).equals("zero_g_hive")){var result=AlvearyFormation.locate(level,pos,tier);if(result.formed()&&contains(result.anchor(),port))return true;}}return false;}
    private static boolean valid(ServerLevel level,BlockPos pos,BlockEntity owner){return !owner.isRemoved()&&owner.getLevel()==level&&controller(level,pos)==owner;}
    private static boolean role(ServerLevel level,BlockPos pos,String expected){return level.hasChunkAt(pos)&&BuiltInRegistries.BLOCK.getKey(level.getBlockState(pos).getBlock()).getPath().endsWith("_"+expected);}
    private static boolean contains(BlockPos o,BlockPos pos){return pos.getX()>=o.getX()-4&&pos.getX()<=o.getX()&&pos.getY()>=o.getY()&&pos.getY()<=o.getY()+4&&pos.getZ()>=o.getZ()-4&&pos.getZ()<=o.getZ();}
    public static boolean inside(BlockEntity owner,BlockPos pos){return contains(AlvearyFormation.anchor(owner),pos);}
    public static IEnergyStorage energy(ServerLevel level,BlockPos pos){var owner=controller(level,pos);if(owner==null)return null;var target=AlvearyRuntime.energy(owner);return new IEnergyStorage(){private boolean live(){return role(level,pos,"energy_port")&&valid(level,pos,owner);}public int receiveEnergy(int n,boolean s){return live()?target.receiveEnergy(n,s):0;}public int extractEnergy(int n,boolean s){return 0;}public int getEnergyStored(){return live()?target.getEnergyStored():0;}public int getMaxEnergyStored(){return target.getMaxEnergyStored();}public boolean canExtract(){return false;}public boolean canReceive(){return live()&&target.canReceive();}};}
    public static IItemHandler items(ServerLevel level,BlockPos pos){var owner=controller(level,pos);if(owner==null)return null;String id=BuiltInRegistries.BLOCK.getKey(level.getBlockState(pos).getBlock()).getPath();boolean output=id.endsWith("output_hatch"),loader=id.endsWith("frame_loader");var target=loader?AlvearyRuntime.frames(owner):AlvearyRuntime.automation(owner);return new IItemHandler(){private boolean live(){return level.hasChunkAt(pos)&&BuiltInRegistries.BLOCK.getKey(level.getBlockState(pos).getBlock()).getPath().equals(id)&&valid(level,pos,owner);}public int getSlots(){return target.getSlots();}public ItemStack getStackInSlot(int i){return live()?target.getStackInSlot(i):ItemStack.EMPTY;}public int getSlotLimit(int i){return target.getSlotLimit(i);}public boolean isItemValid(int i,ItemStack stack){return !output&&live()&&target.isItemValid(i,stack);}public ItemStack insertItem(int i,ItemStack stack,boolean s){return isItemValid(i,stack)?target.insertItem(i,stack,s):stack;}public ItemStack extractItem(int i,int n,boolean s){return output&&live()?target.extractItem(i,n,s):ItemStack.EMPTY;}};}
    public static IFluidHandler fluids(ServerLevel level,BlockPos pos,boolean honey){var owner=controller(level,pos);if(owner==null)return null;var target=new AlvearyFluids(owner);int tank=honey?0:1;return new IFluidHandler(){private boolean live(){return role(level,pos,honey?"honey_port":"fluid_port")&&valid(level,pos,owner);}public int getTanks(){return 1;}public FluidStack getFluidInTank(int i){return live()?target.getFluidInTank(tank):FluidStack.EMPTY;}public int getTankCapacity(int i){return target.getTankCapacity(tank);}public boolean isFluidValid(int i,FluidStack fluid){return !honey&&live()&&target.isFluidValid(tank,fluid);}public int fill(FluidStack fluid,FluidAction action){return isFluidValid(0,fluid)?target.fill(fluid,action):0;}public FluidStack drain(FluidStack fluid,FluidAction action){return honey&&FluidStack.isSameFluidSameComponents(getFluidInTank(0),fluid)?drain(fluid.getAmount(),action):FluidStack.EMPTY;}public FluidStack drain(int n,FluidAction action){return honey&&live()?target.drainTank(tank,n,action):FluidStack.EMPTY;}};}
    public static void eject(BlockEntity owner){if(!(owner.getLevel() instanceof ServerLevel level)||!AlvearyRuntime.formed(owner))return;var inv=GeneticsRuntime.inventory(owner);int tier=AlvearyRuntime.tier(owner);for(int x=0;x<5;x++)for(int y=0;y<5;y++)for(int z=0;z<5;z++){var port=AlvearyFormation.anchor(owner).offset(-x,y,-z);if(!level.hasChunkAt(port)||!BuiltInRegistries.BLOCK.getKey(level.getBlockState(port).getBlock()).getPath().equals("tier"+tier+"_output_hatch")||controller(level,port)!=owner)continue;for(var face:Direction.values()){var dest=port.relative(face);if(!level.hasChunkAt(dest)||inside(owner,dest))continue;var sink=level.getCapability(net.neoforged.neoforge.capabilities.Capabilities.ItemHandler.BLOCK,dest,face.getOpposite());if(sink==null)continue;for(int i=AlvearyRuntime.outputStart(owner);i<inv.getSlots();i++){var stack=inv.getStackInSlot(i).copy();var rest=net.zerog.tweaks.transport.TransportBlockEntity.insert(sink,stack,false);inv.extractItem(i,stack.getCount()-rest.getCount(),false);}}}}
    private AlvearyPorts(){}
}
