package net.zerog.tweaks.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.zerog.tweaks.ZeroGTweaks;

/**
 * ZeroG sound events (assets/zerog_tweaks/sounds.json). The Prism Sentinel set is generated by Design's
 * docs/sentinel-sfx-v1/sentinel_sfx.py: glassy, resonant crystal-construct sounds replacing the vanilla stand-ins.
 */
public final class ZGSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(Registries.SOUND_EVENT, ZeroGTweaks.MODID);

    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_AMBIENT = event("sentinel.ambient");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_HURT = event("sentinel.hurt");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_DEATH = event("sentinel.death");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_CORE_OPEN = event("sentinel.core_open");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_CORE_CLOSE = event("sentinel.core_close");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_PHASE = event("sentinel.phase");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_SHARD_HIT = event("sentinel.shard_hit");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_REFRACT = event("sentinel.refract");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_BEAM_CHARGE = event("sentinel.beam_charge");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_BEAM_FIRE = event("sentinel.beam_fire");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_BEAM_DEFLECT = event("sentinel.beam_deflect");

    // Ore blocks: three families (Design docs/ore-sfx-v1/ore_sfx.py). Place reuses break, fall reuses step, like stone.
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_METAL_BREAK = event("ore.metal.break");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_METAL_STEP = event("ore.metal.step");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_METAL_HIT = event("ore.metal.hit");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_GEM_BREAK = event("ore.gem.break");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_GEM_STEP = event("ore.gem.step");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_GEM_HIT = event("ore.gem.hit");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_DUST_BREAK = event("ore.dust.break");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_DUST_STEP = event("ore.dust.step");
    public static final DeferredHolder<SoundEvent, SoundEvent> ORE_DUST_HIT = event("ore.dust.hit");
    public static final net.neoforged.neoforge.common.util.DeferredSoundType METAL_ORE = new net.neoforged.neoforge.common.util.DeferredSoundType(1F, 1F,
            ORE_METAL_BREAK, ORE_METAL_STEP, ORE_METAL_BREAK, ORE_METAL_HIT, ORE_METAL_STEP);
    public static final net.neoforged.neoforge.common.util.DeferredSoundType GEM_ORE = new net.neoforged.neoforge.common.util.DeferredSoundType(1F, 1F,
            ORE_GEM_BREAK, ORE_GEM_STEP, ORE_GEM_BREAK, ORE_GEM_HIT, ORE_GEM_STEP);
    public static final net.neoforged.neoforge.common.util.DeferredSoundType DUST_ORE = new net.neoforged.neoforge.common.util.DeferredSoundType(1F, 1F,
            ORE_DUST_BREAK, ORE_DUST_STEP, ORE_DUST_BREAK, ORE_DUST_HIT, ORE_DUST_STEP);

    private static DeferredHolder<SoundEvent, SoundEvent> event(String id) {
        return SOUNDS.register(id, () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(ZeroGTweaks.MODID, id)));
    }

    public static void register(IEventBus bus) { SOUNDS.register(bus); }

    private ZGSounds() {}
}
