package net.zerog.tweaks.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.zerog.tweaks.ZeroGTweaks;

/**
 * ZeroG sound events (assets/zerog_tweaks/sounds.json). The Prism Sentinel set is generated by Design's
 * docs/sentinel-sfx-v1/sentinel_sfx.py: glassy, resonant crystal-construct sounds replacing the vanilla stand-ins.
 */
public final class ZGSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(Registries.SOUND_EVENT, ZeroGTweaks.MODID);

    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_AMBIENT = event("sentinel.ambient");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_HURT = event("sentinel.hurt");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_DEATH = event("sentinel.death");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_CORE_OPEN = event("sentinel.core_open");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_CORE_CLOSE = event("sentinel.core_close");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_PHASE = event("sentinel.phase");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_SHARD_HIT = event("sentinel.shard_hit");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_REFRACT = event("sentinel.refract");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_BEAM_CHARGE = event("sentinel.beam_charge");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_BEAM_FIRE = event("sentinel.beam_fire");
    public static final DeferredHolder<SoundEvent, SoundEvent> SENTINEL_BEAM_DEFLECT = event("sentinel.beam_deflect");

    private static DeferredHolder<SoundEvent, SoundEvent> event(String id) {
        return SOUNDS.register(id, () -> SoundEvent.createVariableRangeEvent(ResourceLocation.fromNamespaceAndPath(ZeroGTweaks.MODID, id)));
    }

    public static void register(IEventBus bus) { SOUNDS.register(bus); }

    private ZGSounds() {}
}
