package net.zerog.tweaks.registry;

import java.util.ArrayList;
import java.util.List;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;

/**
 * GENERATED by docs/zero-g-tweaks-bundle/generators/spawn_eggs.py; do not edit by hand.
 * Spawn eggs for the 28 ZeroG mobs and the 10 Shattered Skies creatures (ids "<mob>_spawn_egg").
 * Each egg looks up its entity type by id when used (see {@link ZGSpawnEggItem}), so it starts
 * working the moment that entity is registered; until then it shows a "not in the game yet" message.
 * Shattered Skies eggs try "shatteredskies:<id>" first, then "zerog_tweaks:<id>".
 */
public final class ZGSpawnEggs {
    private ZGSpawnEggs() {}

    public static final List<DeferredItem<ZGSpawnEggItem>> ALL = new ArrayList<>();

    private static DeferredItem<ZGSpawnEggItem> egg(String key, int base, int spots, String... entityIds) {
        DeferredItem<ZGSpawnEggItem> item = ItemInit.ITEMS.register(key + "_spawn_egg",
                () -> new ZGSpawnEggItem(base, spots, entityIds, new Item.Properties()));
        ALL.add(item);
        return item;
    }

    public static final DeferredItem<ZGSpawnEggItem> AMETHYST_STALKER = egg("amethyst_stalker", 0x3B3052, 0xC9A8FF, "shatteredskies:amethyst_stalker", "zerog_tweaks:amethyst_stalker");
    public static final DeferredItem<ZGSpawnEggItem> ASH_STRIDER = egg("ash_strider", 0x1A1A1A, 0xFF8A2A, "zerog_tweaks:ash_strider");
    public static final DeferredItem<ZGSpawnEggItem> AZURE_FOWL = egg("azure_fowl", 0x4A8AD0, 0x3FC9E8, "zerog_tweaks:azure_fowl");
    public static final DeferredItem<ZGSpawnEggItem> BOG_LURKER = egg("bog_lurker", 0x4A5A3A, 0xE8FF80, "zerog_tweaks:bog_lurker");
    public static final DeferredItem<ZGSpawnEggItem> CINDER_HOUND = egg("cinder_hound", 0x221C1A, 0xFFD070, "zerog_tweaks:cinder_hound");
    public static final DeferredItem<ZGSpawnEggItem> CRATER_DRIFTER = egg("crater_drifter", 0x3A3A3A, 0xCFCFCF, "zerog_tweaks:crater_drifter");
    public static final DeferredItem<ZGSpawnEggItem> CRYSTAL_STAG = egg("crystal_stag", 0x2C3D57, 0x3FC9E8, "zerog_tweaks:crystal_stag");
    public static final DeferredItem<ZGSpawnEggItem> DEEP_EEL = egg("deep_eel", 0x5A6A7A, 0x9FF0F0, "zerog_tweaks:deep_eel");
    public static final DeferredItem<ZGSpawnEggItem> DUNE_BURROWER = egg("dune_burrower", 0xD8C090, 0xF0E6D0, "zerog_tweaks:dune_burrower");
    public static final DeferredItem<ZGSpawnEggItem> DUST_GRAZER = egg("dust_grazer", 0xC4683A, 0xE8D0B0, "zerog_tweaks:dust_grazer");
    public static final DeferredItem<ZGSpawnEggItem> DYING_STAR = egg("dying_star", 0xF08A14, 0xFFF0A0, "zerog_tweaks:dying_star");
    public static final DeferredItem<ZGSpawnEggItem> EIDOLON_CAPTAIN = egg("eidolon_captain", 0x2A4050, 0xC4E0EC, "zerog_tweaks:eidolon_captain");
    public static final DeferredItem<ZGSpawnEggItem> FLARE_SPRITE = egg("flare_sprite", 0xFFA030, 0xFFF0A0, "zerog_tweaks:flare_sprite");
    public static final DeferredItem<ZGSpawnEggItem> FROST_WARDEN = egg("frost_warden", 0x5E6E74, 0x9FF0F0, "zerog_tweaks:frost_warden");
    public static final DeferredItem<ZGSpawnEggItem> FROST_YAK = egg("frost_yak", 0xA6B6C0, 0x3A464C, "zerog_tweaks:frost_yak");
    public static final DeferredItem<ZGSpawnEggItem> GILDCRAB = egg("gildcrab", 0xE0A010, 0xFFFFFF, "zerog_tweaks:gildcrab");
    public static final DeferredItem<ZGSpawnEggItem> GLIMMERFISH = egg("glimmerfish", 0x3FC9E8, 0xB0F2FF, "zerog_tweaks:glimmerfish");
    public static final DeferredItem<ZGSpawnEggItem> HOLLOW_SENTINEL = egg("hollow_sentinel", 0x7F8A96, 0xC9A8FF, "shatteredskies:hollow_sentinel", "zerog_tweaks:hollow_sentinel");
    public static final DeferredItem<ZGSpawnEggItem> ICE_LEECH = egg("ice_leech", 0x6AD0C0, 0xD0FBFB, "zerog_tweaks:ice_leech");
    public static final DeferredItem<ZGSpawnEggItem> METEOR_MAW = egg("meteor_maw", 0x3E3739, 0xC9A8FF, "shatteredskies:meteor_maw", "zerog_tweaks:meteor_maw");
    public static final DeferredItem<ZGSpawnEggItem> MOON_HOPPER = egg("moon_hopper", 0xECEEF2, 0xE8A0B0, "zerog_tweaks:moon_hopper");
    public static final DeferredItem<ZGSpawnEggItem> MOSSBACK = egg("mossback", 0x5A4230, 0xC9A8FF, "shatteredskies:mossback", "zerog_tweaks:mossback");
    public static final DeferredItem<ZGSpawnEggItem> PRISM_SENTINEL = egg("prism_sentinel", 0x3FC9E8, 0xE0DCB8, "zerog_tweaks:prism_sentinel");
    public static final DeferredItem<ZGSpawnEggItem> PRISMLING = egg("prismling", 0x1592B8, 0xE8FFFF, "zerog_tweaks:prismling");
    public static final DeferredItem<ZGSpawnEggItem> REGOLITH_CRAWLER = egg("regolith_crawler", 0x9A9AA0, 0x6FE0FF, "zerog_tweaks:regolith_crawler");
    public static final DeferredItem<ZGSpawnEggItem> RIFT_TYRANT = egg("rift_tyrant", 0x2E2624, 0xB48CFF, "zerog_tweaks:rift_tyrant");
    public static final DeferredItem<ZGSpawnEggItem> RIME_STALKER = egg("rime_stalker", 0xDCE6EC, 0x7AE8FF, "zerog_tweaks:rime_stalker");
    public static final DeferredItem<ZGSpawnEggItem> RUST_BEETLE = egg("rust_beetle", 0x9C4424, 0xE89A62, "zerog_tweaks:rust_beetle");
    public static final DeferredItem<ZGSpawnEggItem> SAND_SKITTER = egg("sand_skitter", 0xC8A868, 0x8AC040, "zerog_tweaks:sand_skitter");
    public static final DeferredItem<ZGSpawnEggItem> SCORCH_WYRMLING = egg("scorch_wyrmling", 0xE8661E, 0xFFB040, "zerog_tweaks:scorch_wyrmling");
    public static final DeferredItem<ZGSpawnEggItem> SHARDMOTHER = egg("shardmother", 0x3B3150, 0xC9A8FF, "shatteredskies:shardmother", "zerog_tweaks:shardmother");
    public static final DeferredItem<ZGSpawnEggItem> SLAG_BOAR = egg("slag_boar", 0x3E2A20, 0x8A8A8A, "zerog_tweaks:slag_boar");
    public static final DeferredItem<ZGSpawnEggItem> SLAGJAW = egg("slagjaw", 0x8A8683, 0xC9A8FF, "shatteredskies:slagjaw", "zerog_tweaks:slagjaw");
    public static final DeferredItem<ZGSpawnEggItem> SPLINTER_MITE = egg("splinter_mite", 0x4A3F66, 0xC9A8FF, "shatteredskies:splinter_mite", "zerog_tweaks:splinter_mite");
    public static final DeferredItem<ZGSpawnEggItem> SPLINTER_WISP = egg("splinter_wisp", 0xC9A8FF, 0xE6D4FF, "shatteredskies:splinter_wisp", "zerog_tweaks:splinter_wisp");
    public static final DeferredItem<ZGSpawnEggItem> STORMBITTEN_WYVERN = egg("stormbitten_wyvern", 0x4F8F7A, 0xC9A8FF, "shatteredskies:stormbitten_wyvern", "zerog_tweaks:stormbitten_wyvern");
    public static final DeferredItem<ZGSpawnEggItem> SUN_COLOSSUS = egg("sun_colossus", 0x7A3C1A, 0xFFF0A0, "zerog_tweaks:sun_colossus");
    public static final DeferredItem<ZGSpawnEggItem> TIDEWRAITH = egg("tidewraith", 0x35557A, 0xC9A8FF, "shatteredskies:tidewraith", "zerog_tweaks:tidewraith");

    /** Called from ItemInit so the static fields above are initialised before the register is frozen. */
    static void init() {}
}
