package net.zerog.tweaks.registry;

import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.SmithingTemplateItem;
import net.neoforged.neoforge.registries.DeferredItem;
import net.zerog.tweaks.ZeroGTweaks;

/**
 * GENERATED by docs/zero-g-tweaks-bundle/generators/trims.py; do not edit by hand.
 * Armor trim smithing templates for the 10 ZeroG trim patterns (data/zerog_tweaks/trim_pattern/*).
 * Trim materials (data/zerog_tweaks/trim_material/*) need no Java: they are data only.
 */
public final class ZGTrims {
    private ZGTrims() {}

    public static final List<DeferredItem<SmithingTemplateItem>> ALL = new ArrayList<>();

    private static DeferredItem<SmithingTemplateItem> template(String pattern) {
        ResourceKey<net.minecraft.world.item.armortrim.TrimPattern> key =
                ResourceKey.create(Registries.TRIM_PATTERN, ResourceLocation.fromNamespaceAndPath(ZeroGTweaks.MODID, pattern));
        DeferredItem<SmithingTemplateItem> item = ItemInit.ITEMS.register(pattern + "_armor_trim_smithing_template",
                () -> SmithingTemplateItem.createArmorTrimTemplate(key));
        ALL.add(item);
        return item;
    }

    public static final DeferredItem<SmithingTemplateItem> FRACTURE = template("fracture");
    public static final DeferredItem<SmithingTemplateItem> CRATER = template("crater");
    public static final DeferredItem<SmithingTemplateItem> OLYMPUS = template("olympus");
    public static final DeferredItem<SmithingTemplateItem> GEODE = template("geode");
    public static final DeferredItem<SmithingTemplateItem> RIFT = template("rift");
    public static final DeferredItem<SmithingTemplateItem> HULL = template("hull");
    public static final DeferredItem<SmithingTemplateItem> CORONA = template("corona");
    public static final DeferredItem<SmithingTemplateItem> SURGE = template("surge");
    public static final DeferredItem<SmithingTemplateItem> PRISM = template("prism");
    public static final DeferredItem<SmithingTemplateItem> METEOR = template("meteor");

    /** Called from ItemInit so the static fields above are initialised before the register is frozen. */
    static void init() {}
}
