package net.zerog.tweaks.registry;

import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.SmithingTemplateItem;
import net.neoforged.neoforge.registries.DeferredItem;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Netherite-style upgrade templates for every set on the mining ladder (generated by generators/upgrade_templates.py).
 * Replaces the five plain-Item templates in ItemInit (same ids, so saves and recipes keep working).
 */
public final class ZGUpgradeTemplates {
    private ZGUpgradeTemplates() {}

    /** Ladder order; Nullifite has no template (crafted from ingots, like diamond). */
    public static final List<String> SETS = List.of("ferrox", "moonsteel", "olympium", "cobaltium", "aurelion", "cyrrium", "cerulite", "ruskite", "pyrium", "tectium", "skarnite", "salvium", "palladine", "wraithsteel", "eidolite", "photium", "radiantine", "astrium", "solvanite");

    private static final List<ResourceLocation> BASE_ICONS = List.of(
            ResourceLocation.withDefaultNamespace("item/empty_armor_slot_helmet"),
            ResourceLocation.withDefaultNamespace("item/empty_slot_sword"),
            ResourceLocation.withDefaultNamespace("item/empty_armor_slot_chestplate"),
            ResourceLocation.withDefaultNamespace("item/empty_slot_pickaxe"),
            ResourceLocation.withDefaultNamespace("item/empty_armor_slot_leggings"),
            ResourceLocation.withDefaultNamespace("item/empty_slot_axe"),
            ResourceLocation.withDefaultNamespace("item/empty_armor_slot_boots"),
            ResourceLocation.withDefaultNamespace("item/empty_slot_hoe"),
            ResourceLocation.withDefaultNamespace("item/empty_slot_shovel"));
    private static final List<ResourceLocation> ADDITION_ICONS = List.of(
            ResourceLocation.withDefaultNamespace("item/empty_slot_ingot"));

    public static final Map<String, DeferredItem<SmithingTemplateItem>> ALL = new LinkedHashMap<>();

    static {
        for (String set : SETS) {
            String k = "item.zerog_tweaks.smithing_template." + set + "_upgrade.";
            ALL.put(set, ItemInit.ITEMS.register(set + "_upgrade_smithing_template", () -> new SmithingTemplateItem(
                    Component.translatable(k + "applies_to").withStyle(ChatFormatting.BLUE),
                    Component.translatable(k + "ingredients").withStyle(ChatFormatting.BLUE),
                    Component.translatable("upgrade.zerog_tweaks." + set + "_upgrade").withStyle(ChatFormatting.GRAY),
                    Component.translatable(k + "base_slot_description"),
                    Component.translatable(k + "additions_slot_description"),
                    BASE_ICONS, ADDITION_ICONS)));
        }
    }

    /** Call from ItemInit.register() so the class loads before the registry is frozen. */
    public static void init() {}
}
