package net.zerog.tweaks.gametest;

import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;
import net.zerog.tweaks.genetics.*;

@GameTestHolder("zerog_workflow") @PrefixGameTestTemplate(false)
public final class AlvearyRuntimeGameTests {
    private static BlockEntity place(GameTestHelper h,String id){h.setBlock(new BlockPos(1,1,1),BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath("aeroapiary",id)));return h.getBlockEntity(new BlockPos(1,1,1));}
    private static BlockEntity shell(GameTestHelper h,BlockPos origin){for(int y=0;y<5;y++)for(int x=0;x<5;x++)for(int z=0;z<5;z++){var p=origin.offset(-x,y,-z);boolean core=(y==1||y==2)&&x>=1&&x<=3&&z>=1&&z<=3;String part=y==4?"tier3_roof":x==0&&y==0&&z==0?"tier3_controller":x==1&&y==0&&z==0?"tier3_energy_port":"tier3_casing";if(!BuiltInRegistries.BLOCK.getKey(h.getBlockState(p).getBlock()).getPath().equals("tier3_controller"))h.setBlock(p,core?net.minecraft.world.level.block.Blocks.AIR:BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath("aeroapiary",part)));}return h.getBlockEntity(origin);}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void real_27_frame_progression_migration_and_reload(GameTestHelper h){
        var frame=GeneticsRuntime.product("proven_frame");h.assertTrue(!frame.isEmpty(),"Existing frame missing");
        for(int tier=1;tier<=7;tier++){var be=place(h,"tier"+tier+"_controller");var frames=AlvearyRuntime.frames(be);h.assertTrue(frames.getSlots()==27,"Only visual27 slots");for(int i=0;i<27;i++)h.assertTrue(frames.isItemValid(i,frame)==(i<AlvearyRuntime.FRAME_CAPACITY[tier]),"Tier frame unlock wrong");}
        var be=place(h,"tier7_controller");var original=GeneticsRuntime.inventory(be);original.setStackInSlot(2,frame.copyWithCount(4));original.setStackInSlot(AlvearyRuntime.outputStart(be),new ItemStack(Items.DIAMOND,7));AlvearyRuntime.migrate(be);
        var frames=AlvearyRuntime.frames(be);int count=0;for(int i=0;i<27;i++)count+=frames.getStackInSlot(i).getCount();h.assertTrue(count==4&&original.getStackInSlot(2).isEmpty(),"Frame migration duplicated/lost contents");h.assertTrue(original.getStackInSlot(AlvearyRuntime.outputStart(be)).getCount()==7,"Migration overwrote old outputs");
        AlvearyRuntime.energy(be).receiveEnergy(100000,false);var tag=be.saveWithFullMetadata(h.getLevel().registryAccess());var restored=BlockEntity.loadStatic(be.getBlockPos(),be.getBlockState(),tag,h.getLevel().registryAccess());restored.setLevel(h.getLevel());h.assertTrue(AlvearyRuntime.frames(restored).getStackInSlot(3).getCount()==1&&AlvearyRuntime.energy(restored).getEnergyStored()==100000,"Frame/FE persistence failed");
        var cap=AlvearyRuntime.automation(be);h.assertTrue(!cap.isItemValid(AlvearyRuntime.outputStart(be),new ItemStack(Items.STONE)),"Automation writes output");h.assertTrue(cap.extractItem(original.getSlots(),1,false).isEmpty(),"Automation steals loaded frames");h.succeed();
    }
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void controller_requires_structure_and_tank_tiers(GameTestHelper h){
        var low=place(h,"tier1_controller");h.assertTrue(AlvearyRuntime.status(low)==12,"Unformed controller produced items");var lowFluids=new AlvearyFluids(low);h.assertTrue(lowFluids.getTankCapacity(0)==0&&lowFluids.getTankCapacity(1)==0,"Low-tier tanks unsealed");
        var high=place(h,"tier7_controller");var fluids=new AlvearyFluids(high);var starlight=BuiltInRegistries.FLUID.get(ResourceLocation.parse("zerog_tweaks:liquid_starlight"));var stack=new FluidStack(starlight,1000);h.assertTrue(fluids.fill(stack,IFluidHandler.FluidAction.SIMULATE)==1000&&fluids.getFluidInTank(1).isEmpty(),"Catalyst simulation mutated tank");fluids.fill(stack,IFluidHandler.FluidAction.EXECUTE);h.assertTrue(fluids.getFluidInTank(1).getAmount()==1000&&fluids.getTankCapacity(0)==8000,"Actual tanks missing");
        h.assertTrue(fluids.fill(new FluidStack(net.minecraft.world.level.material.Fluids.LAVA,1000),IFluidHandler.FluidAction.EXECUTE)==0,"Wrong alveary catalyst accepted");var player=h.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);player.setPos(high.getBlockPos().getCenter());var menu=new AlvearyMenu(1,player.getInventory(),high);h.assertTrue(!menu.clickMenuButton(player,999)&&!menu.clickMenuButton(player,4),"Invalid/unconfirmed void request accepted");player.setPos(high.getBlockPos().getCenter().add(100,0,0));h.assertTrue(!menu.clickMenuButton(player,1),"Distant controller command accepted");h.succeed();
    }
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void honey_collection_consumes_real_bottle_returns_glass(GameTestHelper h){var be=place(h,"tier3_controller");var inv=GeneticsRuntime.inventory(be);var bottle=BuiltInRegistries.ITEM.get(ResourceLocation.parse("zerog_tweaks:moon_honey_bottle"));int slot=AlvearyRuntime.outputStart(be);inv.setStackInSlot(slot,new ItemStack(bottle,2));AlvearyRuntime.collectHoney(be);h.assertTrue(new AlvearyFluids(be).getFluidInTank(0).getAmount()==250,"Honey tank did not collect actual product");h.assertTrue(inv.getStackInSlot(slot).getCount()==1,"Honey bottle not consumed exactly once");int glass=0;for(int i=slot;i<inv.getSlots();i++)if(inv.getStackInSlot(i).is(Items.GLASS_BOTTLE))glass+=inv.getStackInSlot(i).getCount();h.assertTrue(glass==1,"Glass bottle lost/duplicated");h.succeed();}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void formed_controller_uses_actual_pb_recipe_components_and_honey_save(GameTestHelper h){
        try {
            var origin=new BlockPos(4,1,4);
            for(int y=0;y<5;y++)for(int x=0;x<5;x++)for(int z=0;z<5;z++){var p=origin.offset(-x,y,-z);boolean core=(y==1||y==2)&&x>=1&&x<=3&&z>=1&&z<=3;String part=y==4?"tier3_roof":x==0&&y==0&&z==0?"tier3_controller":x==1&&y==0&&z==0?"tier3_energy_port":"tier3_casing";h.setBlock(p,core?net.minecraft.world.level.block.Blocks.AIR:BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath("aeroapiary",part)));}
            h.setBlock(new BlockPos(0,1,4),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("aeroapiary:tier3_honey_port")));
            var be=h.getBlockEntity(origin);be.getClass().getMethod("updateFormation").invoke(be);h.assertTrue(AlvearyRuntime.formed(be),"Real shell not formed: "+be.getClass().getMethod("getLastStructureError").invoke(be));
            String pb="cy.jdkdigital.productivebees.";var bee=(net.minecraft.world.entity.animal.Bee)BuiltInRegistries.ENTITY_TYPE.get(ResourceLocation.parse("productivebees:configurable_bee")).create(h.getLevel());bee.getClass().getMethod("setBeeType",String.class).invoke(bee,"productivebees:iron");
            Class<?> attr=Class.forName(pb+"util.GeneAttribute"),value=Class.forName(pb+"util.GeneValue");var set=bee.getClass().getMethod("setAttributeValue",attr,value);String[] values={"PRODUCTIVITY_HIGH","ENDURANCE_STRONG","TEMPER_PASSIVE","BEHAVIOR_DIURNAL","WEATHER_TOLERANCE_ANY"};for(int i=0;i<5;i++)set.invoke(bee,attr.getField(ProductiveBeeGenes.GENES[i].toUpperCase(java.util.Locale.ROOT)).get(null),value.getField(values[i]).get(null));
            var cage=new ItemStack(BuiltInRegistries.ITEM.get(ResourceLocation.parse("productivebees:bee_cage")));Class.forName(pb+"common.item.BeeCage").getMethod("captureEntity",net.minecraft.world.entity.animal.Bee.class,ItemStack.class).invoke(null,bee,cage);var expected=ProductiveBeeProduction.outputs(cage,h.getLevel());h.assertTrue(!expected.isEmpty(),"Installed iron bee recipe not resolved");
            GeneticsRuntime.inventory(be).setStackInSlot(0,cage);AlvearyRuntime.energy(be).receiveEnergy(100000,false);h.getLevel().setDayTime(1000);for(int i=0;i<AlvearyRuntime.cycle(be);i++)AlvearyRuntime.tick(be);
            var inv=GeneticsRuntime.inventory(be);boolean matching=false;for(var product:expected)if(product.chance()==1){int count=0;for(int i=AlvearyRuntime.outputStart(be);i<inv.getSlots();i++)if(ItemStack.isSameItemSameComponents(inv.getStackInSlot(i),product.item()))count+=inv.getStackInSlot(i).getCount();h.assertTrue(count>=ProductiveBeeProduction.productiveQuantity(product.min(),product.productivity())&&count<=product.maximum().getCount(),"PB gene output quantity differs from authoritative hive rule: "+count);matching=true;}h.assertTrue(matching,"Real PB component-bearing recipe output missing");h.assertTrue(ProductiveBeeProduction.productiveQuantity(1,2)==3&&ProductiveBeeProduction.productiveQuantity(2,2)==6&&ProductiveBeeProduction.productiveQuantity(2,0)==2,"PB single/multiple output arithmetic changed");
            var honey=BuiltInRegistries.FLUID.get(ResourceLocation.parse("zerog_tweaks:moon_honey"));
            var port=h.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.FluidHandler.BLOCK,h.absolutePos(new BlockPos(0,1,4)),null);
            h.assertTrue(port!=null,"Production honey port missing");
            var preview=port.drain(250,IFluidHandler.FluidAction.SIMULATE);
            h.assertTrue(preview.getAmount()==250&&preview.getFluid()==honey,"Completed cycle did not supply250mB Moon Honey alongside its combs");
            h.assertTrue(new AlvearyFluids(be).getFluidInTank(0).getAmount()==250,"Port simulation consumed produced honey");
            h.assertTrue(port.drain(250,IFluidHandler.FluidAction.EXECUTE).getAmount()==250&&port.drain(1,IFluidHandler.FluidAction.SIMULATE).isEmpty(),"Production honey extraction duplicated/lost fluid");
            var fluids=new AlvearyFluids(be);
            h.assertTrue(fluids.fill(new FluidStack(honey,8000),IFluidHandler.FluidAction.EXECUTE)==8000,"Full-tank fixture failed");
            int energyBefore=AlvearyRuntime.energy(be).getEnergyStored();
            int progressBefore=AlvearyRuntime.state(be).getInt("progress");
            for(int i=0;i<10;i++)AlvearyRuntime.tick(be);
            h.assertTrue(AlvearyRuntime.status(be)==13&&AlvearyRuntime.energy(be).getEnergyStored()==energyBefore&&AlvearyRuntime.state(be).getInt("progress")==progressBefore,"Full honey tank consumed energy or cycle progress");
            port.drain(8000,IFluidHandler.FluidAction.EXECUTE);
            var marsHoney=BuiltInRegistries.FLUID.get(ResourceLocation.parse("zerog_tweaks:mars_honey"));
            h.assertTrue(fluids.fill(new FluidStack(marsHoney,250),IFluidHandler.FluidAction.EXECUTE)==250,"Different-honey fixture failed");
            AlvearyRuntime.tick(be);
            h.assertTrue(AlvearyRuntime.status(be)==13&&AlvearyRuntime.energy(be).getEnergyStored()==energyBefore,"Different honey was mixed or charged energy");
            port.drain(250,IFluidHandler.FluidAction.EXECUTE);
            AlvearyRuntime.tick(be);
            h.assertTrue(AlvearyRuntime.energy(be).getEnergyStored()==energyBefore-60&&AlvearyRuntime.state(be).getInt("progress")==progressBefore+1,"Drained tank did not resume paid processing");
            fluids.fill(new FluidStack(honey,750),IFluidHandler.FluidAction.EXECUTE);var restored=BlockEntity.loadStatic(be.getBlockPos(),be.getBlockState(),be.saveWithFullMetadata(h.getLevel().registryAccess()),h.getLevel().registryAccess());restored.setLevel(h.getLevel());h.assertTrue(new AlvearyFluids(restored).getFluidInTank(0).getAmount()==750,"Honey tank lost on save/reload");h.succeed();
        }catch(ReflectiveOperationException ex){throw new RuntimeException(ex);}
    }
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void physical_ports_forward_cables_outputs_honey_and_fail_on_broken_shell(GameTestHelper h){var owner=shell(h,new BlockPos(4,1,4));for(var entry:java.util.Map.of(new BlockPos(2,1,4),"tier3_input_hatch",new BlockPos(1,1,4),"tier3_output_hatch",new BlockPos(0,1,4),"tier3_honey_port").entrySet())h.setBlock(entry.getKey(),BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath("aeroapiary",entry.getValue())));var energyPos=h.absolutePos(new BlockPos(3,1,4));var energy=h.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.EnergyStorage.BLOCK,energyPos,null);h.assertTrue(energy!=null&&energy.canReceive()&&!energy.canExtract(),"Physical energy port absent or reversed");h.setBlock(new BlockPos(3,1,5),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("zerog_tweaks:copper_energy_conduit")));h.setBlock(new BlockPos(3,1,6),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("zerog_tweaks:energy_port")));var cable=(net.zerog.tweaks.transport.TransportBlockEntity)h.getBlockEntity(new BlockPos(3,1,5));var source=(net.zerog.tweaks.transport.TransportBlockEntity)h.getBlockEntity(new BlockPos(3,1,6));source.stored=10000;cable.modes[net.minecraft.core.Direction.SOUTH.ordinal()]=2;cable.modes[net.minecraft.core.Direction.NORTH.ordinal()]=1;net.zerog.tweaks.transport.TransportBlockEntity.tick(h.getLevel(),cable.getBlockPos(),cable.getBlockState(),cable);h.assertTrue(AlvearyRuntime.energy(owner).getEnergyStored()==1000&&source.stored==9000,"Cable did not reach controller through actual energy port");
        var inv=GeneticsRuntime.inventory(owner);int slot=AlvearyRuntime.outputStart(owner);inv.setStackInSlot(slot,new ItemStack(Items.DIAMOND,7));var output=h.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.ItemHandler.BLOCK,h.absolutePos(new BlockPos(1,1,4)),null);var input=h.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.ItemHandler.BLOCK,h.absolutePos(new BlockPos(2,1,4)),null);h.assertTrue(output!=null&&input!=null&&output.extractItem(slot,2,false).getCount()==2&&inv.getStackInSlot(slot).getCount()==5,"Output hatch did not reach real products");h.assertTrue(output.insertItem(slot,new ItemStack(Items.STONE),false).getCount()==1&&input.extractItem(slot,1,false).isEmpty(),"Hatch direction filters reversed");
        new AlvearyFluids(owner).fill(new FluidStack(BuiltInRegistries.FLUID.get(ResourceLocation.parse("zerog_tweaks:moon_honey")),750),IFluidHandler.FluidAction.EXECUTE);var honey=h.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.FluidHandler.BLOCK,h.absolutePos(new BlockPos(0,1,4)),null);h.assertTrue(honey!=null&&honey.drain(250,IFluidHandler.FluidAction.SIMULATE).getAmount()==250&&new AlvearyFluids(owner).getFluidInTank(0).getAmount()==750,"Honey port simulation wrong");honey.drain(250,IFluidHandler.FluidAction.EXECUTE);h.assertTrue(new AlvearyFluids(owner).getFluidInTank(0).getAmount()==500,"Honey port not linked to tank");
        h.setBlock(new BlockPos(1,1,4),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("aeroapiary:tier3_input_hatch")));h.assertTrue(output.extractItem(slot,1,false).isEmpty(),"Cached output handler retained authority after role change");h.setBlock(new BlockPos(1,1,4),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("aeroapiary:tier3_output_hatch")));h.setBlock(new BlockPos(0,1,4),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("aeroapiary:tier3_casing")));h.assertTrue(honey.drain(250,IFluidHandler.FluidAction.EXECUTE).isEmpty(),"Cached honey handler retained authority after replacement");h.setBlock(new BlockPos(0,1,4),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("aeroapiary:tier3_honey_port")));
        var distant=new BlockPos(1000000,owner.getBlockPos().getY(),1000000);h.assertTrue(!h.getLevel().hasChunkAt(distant)&&!AlvearyPorts.footprintLoaded(h.getLevel(),distant)&&!h.getLevel().hasChunkAt(distant),"Formation preflight loaded an unavailable footprint chunk");h.setBlock(new BlockPos(4,5,4),net.minecraft.world.level.block.Blocks.AIR);h.assertTrue(energy.receiveEnergy(1000,false)==0&&honey.drain(250,IFluidHandler.FluidAction.EXECUTE).isEmpty()&&output.extractItem(slot,1,false).isEmpty(),"Cached port accessed stale/broken formation");h.succeed();}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void shared_wall_port_refuses_ambiguous_controllers(GameTestHelper h){var first=shell(h,new BlockPos(4,1,4));var shared=new BlockPos(4,2,2);h.setBlock(shared,BuiltInRegistries.BLOCK.get(ResourceLocation.parse("aeroapiary:tier3_energy_port")));var cap=AlvearyPorts.energy(h.getLevel(),h.absolutePos(shared));h.assertTrue(cap!=null&&cap.receiveEnergy(10,false)==10,"Single-owner shared-wall port missing");var second=shell(h,new BlockPos(8,1,4));h.setBlock(shared,BuiltInRegistries.BLOCK.get(ResourceLocation.parse("aeroapiary:tier3_energy_port")));h.assertTrue(AlvearyPorts.controller(h.getLevel(),h.absolutePos(shared))==null&&cap.receiveEnergy(10,false)==0,"Ambiguous port chose one of two valid controllers");h.assertTrue(AlvearyRuntime.formed(first)&&AlvearyRuntime.formed(second),"Ambiguity test shells were not both valid");h.succeed();}
}
