package net.zerog.tweaks.gametest;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.FluidUtil;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;
import net.zerog.tweaks.storage.*;

@GameTestHolder("zerog_workflow") @PrefixGameTestTemplate(false)
public final class StorageTankGameTests {
    private static StorageTankBlockEntity place(GameTestHelper h,BlockPos pos,int tier){h.setBlock(pos,StorageTankRegistry.BLOCKS.get(tier).get());return(StorageTankBlockEntity)h.getBlockEntity(pos);}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void six_capacities_simulation_io_and_reload(GameTestHelper h){for(int tier=0;tier<6;tier++){var be=place(h,new BlockPos(1,1,1),tier);var handler=be.handler(Direction.NORTH);var water=new FluidStack(net.minecraft.world.level.material.Fluids.WATER,6000000);h.assertTrue(handler.fill(water,IFluidHandler.FluidAction.SIMULATE)==StorageTankRegistry.CAPACITIES[tier]&&be.tank.isEmpty(),"Tank simulation changed contents or wrong capacity");handler.fill(water,IFluidHandler.FluidAction.EXECUTE);h.assertTrue(be.tank.getFluidAmount()==StorageTankRegistry.CAPACITIES[tier]&&handler.fill(new FluidStack(net.minecraft.world.level.material.Fluids.LAVA,1000),IFluidHandler.FluidAction.EXECUTE)==0,"Mixed fluids or capacity exceeded");be.modes[Direction.NORTH.ordinal()]=1;h.assertTrue(handler.drain(1000,IFluidHandler.FluidAction.EXECUTE).isEmpty(),"Input face drained");be.modes[Direction.NORTH.ordinal()]=2;h.assertTrue(handler.fill(water,IFluidHandler.FluidAction.EXECUTE)==0&&handler.drain(1000,IFluidHandler.FluidAction.SIMULATE).getAmount()==1000,"Output direction/simulation wrong");be.modes[Direction.NORTH.ordinal()]=3;h.assertTrue(handler.drain(1000,IFluidHandler.FluidAction.EXECUTE).isEmpty(),"Disabled face drained");var restored=(StorageTankBlockEntity)BlockEntity.loadStatic(be.getBlockPos(),be.getBlockState(),be.saveWithFullMetadata(h.getLevel().registryAccess()),h.getLevel().registryAccess());h.assertTrue(restored.tank.getFluidAmount()==be.capacity()&&restored.modes[Direction.NORTH.ordinal()]==3,"Tank contents/control lost on reload");h.getLevel().removeBlock(be.getBlockPos(),false);h.assertTrue(handler.drain(1000,IFluidHandler.FluidAction.EXECUTE).isEmpty(),"Cached removed tank handler leaked contents");}h.succeed();}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void upgrade_break_and_real_placement_preserve_one_tank(GameTestHelper h){var pos=new BlockPos(1,1,1);var be=place(h,pos,0);be.tank.fill(new FluidStack(net.minecraft.world.level.material.Fluids.WATER,4000),IFluidHandler.FluidAction.EXECUTE);be.modes[0]=2;var refund=StorageTankInteraction.upgrade(h.getLevel(),be.getBlockPos(),StorageTankRegistry.BLOCKS.get(5).get());var upgraded=(StorageTankBlockEntity)h.getBlockEntity(pos);h.assertTrue(refund.getCount()==1&&!refund.has(net.minecraft.core.component.DataComponents.BLOCK_ENTITY_DATA)&&upgraded.tank.getFluidAmount()==4000&&upgraded.capacity()==5000000&&upgraded.modes[0]==2,"Upgrade lost/duplicated contents or controls");h.assertTrue(StorageTankInteraction.upgrade(h.getLevel(),upgraded.getBlockPos(),StorageTankRegistry.BLOCKS.get(0).get()).isEmpty(),"Downgrade silently truncated fluid");var builder=new net.minecraft.world.level.storage.loot.LootParams.Builder(h.getLevel()).withParameter(net.minecraft.world.level.storage.loot.parameters.LootContextParams.BLOCK_ENTITY,upgraded).withParameter(net.minecraft.world.level.storage.loot.parameters.LootContextParams.BLOCK_STATE,upgraded.getBlockState()).withParameter(net.minecraft.world.level.storage.loot.parameters.LootContextParams.ORIGIN,upgraded.getBlockPos().getCenter()).withParameter(net.minecraft.world.level.storage.loot.parameters.LootContextParams.TOOL,ItemStack.EMPTY);var drops=upgraded.getBlockState().getDrops(builder);h.assertTrue(drops.size()==1&&drops.get(0).getCount()==1&&drops.get(0).has(net.minecraft.core.component.DataComponents.BLOCK_ENTITY_DATA),"Break drop lost fluid or duplicated shell");h.setBlock(pos,net.minecraft.world.level.block.Blocks.AIR);h.setBlock(pos.below(),net.minecraft.world.level.block.Blocks.STONE);var player=h.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);player.setPos(h.absolutePos(pos).getCenter().add(0,0,2));player.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,drops.get(0));var context=new net.minecraft.world.item.context.BlockPlaceContext(h.getLevel(),player,net.minecraft.world.InteractionHand.MAIN_HAND,player.getMainHandItem(),new net.minecraft.world.phys.BlockHitResult(h.absolutePos(pos.below()).getCenter().add(0,.5,0),Direction.UP,h.absolutePos(pos.below()),false));var result=((net.minecraft.world.item.BlockItem)player.getMainHandItem().getItem()).place(context);h.assertTrue(result.consumesAction()&&player.getMainHandItem().isEmpty()&&h.getBlockEntity(pos) instanceof StorageTankBlockEntity placed&&placed.tank.getFluidAmount()==4000&&placed.modes[0]==2,"Real block item placement failed to restore saved fluid");h.succeed();}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void buckets_and_pipe_transfer_conserve_fluid_and_menu_authority(GameTestHelper h){var source=place(h,new BlockPos(1,1,1),0);var player=h.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);player.setPos(source.getBlockPos().getCenter());player.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new ItemStack(Items.WATER_BUCKET));h.assertTrue(FluidUtil.interactWithFluidHandler(player,net.minecraft.world.InteractionHand.MAIN_HAND,h.getLevel(),source.getBlockPos(),Direction.NORTH)&&source.tank.getFluidAmount()==1000&&player.getMainHandItem().is(Items.BUCKET),"Bucket insertion not conserved");h.assertTrue(FluidUtil.interactWithFluidHandler(player,net.minecraft.world.InteractionHand.MAIN_HAND,h.getLevel(),source.getBlockPos(),Direction.NORTH)&&source.tank.isEmpty()&&player.getMainHandItem().is(Items.WATER_BUCKET),"Bucket collection not conserved");source.tank.fill(new FluidStack(net.minecraft.world.level.material.Fluids.WATER,1000),IFluidHandler.FluidAction.EXECUTE);h.setBlock(new BlockPos(2,1,1),BuiltInRegistries.BLOCK.get(ResourceLocation.parse("zerog_tweaks:copper_fluid_pipe")));var pipe=(net.zerog.tweaks.transport.TransportBlockEntity)h.getBlockEntity(new BlockPos(2,1,1));var sink=place(h,new BlockPos(3,1,1),0);pipe.modes[Direction.WEST.ordinal()]=2;pipe.modes[Direction.EAST.ordinal()]=1;net.zerog.tweaks.transport.TransportBlockEntity.tick(h.getLevel(),pipe.getBlockPos(),pipe.getBlockState(),pipe);h.assertTrue(source.tank.getFluidAmount()+pipe.tank.getFluidAmount()+sink.tank.getFluidAmount()==1000&&sink.tank.getFluidAmount()==250,"Pipe/tank fluid loss or tier throughput mismatch");var menu=new StorageTankMenu(1,player.getInventory(),source);h.assertTrue(!menu.clickMenuButton(player,99)&&menu.clickMenuButton(player,0),"Tank control validation failed");player.setPos(source.getBlockPos().getCenter().add(100,0,0));h.assertTrue(!menu.clickMenuButton(player,0),"Remote player altered tank controls");h.succeed();}
}
