package net.zerog.tweaks.gametest;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;
import net.zerog.tweaks.transport.*;

@GameTestHolder("zerog_workflow") @PrefixGameTestTemplate(false)
public final class TransportGameTests {
    private static TransportBlockEntity place(GameTestHelper h,BlockPos pos,String id){h.setBlock(pos,BuiltInRegistries.BLOCK.get(ResourceLocation.fromNamespaceAndPath("zerog_tweaks",id)));return (TransportBlockEntity)h.getBlockEntity(pos);}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void tier_buffer_simulation_filters_and_persistence(GameTestHelper h){
        for(int i=0;i<6;i++){
            var be=place(h,new BlockPos(1,1,1),TransportTier.ALL[i].name()+"_energy_cell");var cap=be.energy(null);
            h.assertTrue(cap.receiveEnergy(Integer.MAX_VALUE,true)==TransportTier.ALL[i].capacity()&&cap.getEnergyStored()==0,"Simulation changed cell");cap.receiveEnergy(Integer.MAX_VALUE,false);
            h.assertTrue(cap.getEnergyStored()==TransportTier.ALL[i].capacity(),"Incorrect cell capacity");
            var restored=(TransportBlockEntity)BlockEntity.loadStatic(be.getBlockPos(),be.getBlockState(),be.saveWithFullMetadata(h.getLevel().registryAccess()),h.getLevel().registryAccess());h.assertTrue(restored.stored==be.stored,"Cell contents lost on reload");
        }
        var be=place(h,new BlockPos(1,1,1),"copper_item_tube");be.itemFilter="minecraft:diamond";
        h.assertTrue(be.itemHandler(null).insertItem(0,new ItemStack(Items.STONE),false).getCount()==1,"Whitelist accepted wrong item");
        h.assertTrue(be.itemHandler(null).insertItem(0,new ItemStack(Items.DIAMOND),true).isEmpty()&&be.items.getStackInSlot(0).isEmpty(),"Item simulation mutated buffer");be.blacklist=true;
        h.assertTrue(be.itemHandler(null).insertItem(0,new ItemStack(Items.DIAMOND),false).getCount()==1,"Blacklist accepted blocked item");
        be.modes[Direction.NORTH.ordinal()]=3;h.assertTrue(be.itemHandler(Direction.NORTH).extractItem(0,1,false).isEmpty(),"Disabled face extracts");h.succeed();
    }
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void network_energy_conservation_and_fluid_tier(GameTestHelper h){
        var src=place(h,new BlockPos(1,1,1),"energy_port");var line=place(h,new BlockPos(2,1,1),"copper_energy_conduit");var dst=place(h,new BlockPos(3,1,1),"energy_port");src.stored=10000;line.modes[Direction.WEST.ordinal()]=2;line.modes[Direction.EAST.ordinal()]=1;
        var sourceCapability=h.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.EnergyStorage.BLOCK,src.getBlockPos(),Direction.EAST);var sinkCapability=h.getLevel().getCapability(net.neoforged.neoforge.capabilities.Capabilities.EnergyStorage.BLOCK,dst.getBlockPos(),Direction.WEST);
        h.assertTrue(sourceCapability!=null&&sinkCapability!=null,"Actual transport FE capabilities absent");h.assertTrue(sourceCapability.extractEnergy(1000,true)==1000&&sinkCapability.receiveEnergy(1000,true)==1000,"Actual transport FE faces reject expected transfer");
        TransportBlockEntity.tick(h.getLevel(),line.getBlockPos(),line.getBlockState(),line);
        h.assertTrue(src.stored+line.stored+dst.stored==10000&&dst.stored==1000,"Energy conservation/rate failed: source="+src.stored+", line="+line.stored+", destination="+dst.stored+", positions="+src.getBlockPos()+" / "+line.getBlockPos()+" / "+dst.getBlockPos());
        var pipe=place(h,new BlockPos(2,1,1),"copper_fluid_pipe");var water=new FluidStack(net.minecraft.world.level.material.Fluids.WATER,1000);
        h.assertTrue(pipe.fluidHandler(null).fill(water,IFluidHandler.FluidAction.SIMULATE)==1000&&pipe.tank.isEmpty(),"Fluid simulation changed tank");pipe.fluidHandler(null).fill(water,IFluidHandler.FluidAction.EXECUTE);
        var lava=new FluidStack(net.minecraft.world.level.material.Fluids.LAVA,1000);h.assertTrue(pipe.fluidHandler(null).fill(lava,IFluidHandler.FluidAction.EXECUTE)==0,"Mixed network fluids");
        h.assertTrue(TransportTier.minimumFluidTier("zerog_tweaks:solar_plasma")==5&&TransportTier.minimumFluidTier("zerog_tweaks:acid")==2,"Dangerous fluid tier wrong");h.succeed();
    }
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void null_link_shared_buffer_fees_and_stale_partner_safety(GameTestHelper h){
        var first=place(h,new BlockPos(1,1,1),"null_link");var second=place(h,new BlockPos(3,1,1),"null_link");String dim=h.getLevel().dimension().location().toString();first.partner=second.getBlockPos();first.partnerDimension=dim;second.partner=first.getBlockPos();second.partnerDimension=dim;
        var owner=first.owner();h.assertTrue(owner!=null&&second.owner()==owner,"Endpoints not sharing canonical owner");var remote=owner==first?second:first;owner.stored=10000;var items=remote.itemHandler(null);
        h.assertTrue(items.insertItem(0,new ItemStack(Items.DIAMOND,10),true).isEmpty()&&owner.items.getStackInSlot(0).isEmpty()&&owner.stored==10000,"NullLink simulation mutated content/FE");items.insertItem(0,new ItemStack(Items.DIAMOND,10),false);
        h.assertTrue(owner.items.getStackInSlot(0).getCount()==10&&remote.itemHandler(null).getStackInSlot(0).getCount()==10&&owner.stored==9980,"Remote insertion duplicated contents or charged wrong fee");
        h.assertTrue(items.extractItem(0,5,false).getCount()==5&&owner.items.getStackInSlot(0).getCount()==5&&owner.stored==9970,"Remote extraction fee/conservation wrong");
        var fluid=remote.fluidHandler(null);fluid.fill(new FluidStack(net.minecraft.world.level.material.Fluids.WATER,250),IFluidHandler.FluidAction.EXECUTE);h.assertTrue(owner.tank.getFluidAmount()==250&&owner.stored==9720,"Fluid sharing/fee wrong");
        var energy=remote.energy(null);h.assertTrue(energy.extractEnergy(1000,false)==1000&&owner.stored==8710,"Remote FE fee wrong");
        owner.partner=new BlockPos(30000000,100,30000000);h.assertTrue(remote.owner()==null&&items.extractItem(0,5,false).isEmpty()&&energy.extractEnergy(1000,false)==0,"Cached capability accessed absent/unloaded partner");h.succeed();
    }
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void upgrades_ghost_filters_and_port_cell_controls(GameTestHelper h){
        var be=place(h,new BlockPos(1,1,1),"copper_item_tube");be.items.setStackInSlot(0,new ItemStack(Items.DIAMOND,17));be.colour=5;be.priorities[0]=7;var player=h.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);player.setPos(be.getBlockPos().getCenter());var menu=new TransportMenu(1,player.getInventory(),be);menu.setCarried(new ItemStack(Items.DIAMOND,8));menu.clicked(menu.machineSlots,0,net.minecraft.world.inventory.ClickType.PICKUP,player);h.assertTrue(menu.getCarried().getCount()==8&&be.ghostItems.getStackInSlot(0).getCount()==1,"Ghost template consumed or duplicated physical items");h.assertTrue(menu.quickMoveStack(player,menu.machineSlots).isEmpty(),"Ghost filter became loot");h.assertTrue(!be.permittedItem(new ItemStack(Items.STONE))&&be.permittedItem(new ItemStack(Items.DIAMOND)),"Ghost whitelist not enforced");
        var replacement=(TransportBlock)BuiltInRegistries.BLOCK.get(ResourceLocation.parse("zerog_tweaks:nullifite_item_tube"));var refund=TransportInteraction.upgrade(h.getLevel(),be.getBlockPos(),replacement);var upgraded=(TransportBlockEntity)h.getLevel().getBlockEntity(be.getBlockPos());h.assertTrue(!refund.isEmpty()&&upgraded.items.getStackInSlot(0).getCount()==17&&upgraded.ghostItems.getStackInSlot(0).getCount()==1&&upgraded.colour==5&&upgraded.priorities[0]==7,"Upgrade lost contents/filter/configuration");
        var cell=place(h,new BlockPos(2,1,1),"copper_energy_cell");h.assertTrue(cell.energy(Direction.EAST).canReceive()&&!cell.energy(Direction.EAST).canExtract(),"Cell default side not input");cell.cycleFace(Direction.EAST);h.assertTrue(cell.energy(Direction.EAST).canExtract()&&!cell.energy(Direction.EAST).canReceive(),"Cell wrench output toggle broken");
        var context=new net.minecraft.world.item.context.BlockPlaceContext(h.getLevel(),player,net.minecraft.world.InteractionHand.MAIN_HAND,new ItemStack(cell.block()),new net.minecraft.world.phys.BlockHitResult(cell.getBlockPos().getCenter(),Direction.EAST,cell.getBlockPos(),false));var placedState=cell.block().getStateForPlacement(context);h.setBlock(new BlockPos(4,1,1),placedState);var placedCell=(TransportBlockEntity)h.getBlockEntity(new BlockPos(4,1,1));h.assertTrue(placedCell.energy(Direction.WEST).canExtract()&&!placedCell.energy(Direction.WEST).canReceive(),"Placement-contact face not cell output");var savedCell=(TransportBlockEntity)BlockEntity.loadStatic(placedCell.getBlockPos(),placedCell.getBlockState(),placedCell.saveWithFullMetadata(h.getLevel().registryAccess()),h.getLevel().registryAccess());h.assertTrue(savedCell.output(Direction.WEST)&&!savedCell.input(Direction.WEST),"Placement-side mode lost on reload");
        var port=place(h,new BlockPos(3,1,1),"energy_port");port.cycleFace(Direction.NORTH);h.assertTrue(port.getBlockState().getValue(TransportBlock.MODE)==TransportBlock.PortMode.INPUT&&!port.energy(Direction.SOUTH).canExtract(),"Port input mode only cosmetic");port.cycleFace(Direction.NORTH);h.assertTrue(port.getBlockState().getValue(TransportBlock.MODE)==TransportBlock.PortMode.OUTPUT&&!port.energy(Direction.SOUTH).canReceive(),"Port output mode only cosmetic");h.succeed();
    }
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void remote_menu_exact_fee_rollback_and_no_world_drop(GameTestHelper h){var first=place(h,new BlockPos(1,1,1),"null_link");var second=place(h,new BlockPos(3,1,1),"null_link");String dim=h.getLevel().dimension().location().toString();first.partner=second.getBlockPos();first.partnerDimension=dim;second.partner=first.getBlockPos();second.partnerDimension=dim;var owner=first.owner();var remote=owner==first?second:first;var player=h.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);player.setPos(remote.getBlockPos().getCenter());var menu=new TransportMenu(1,player.getInventory(),remote);owner.items.setStackInSlot(0,new ItemStack(Items.DIAMOND,5));owner.stored=9;menu.clicked(0,0,net.minecraft.world.inventory.ClickType.PICKUP,player);h.assertTrue(owner.items.getStackInSlot(0).getCount()==5&&menu.getCarried().isEmpty()&&owner.stored==9,"Insufficient-FE remote click was not rolled back");owner.stored=10;menu.clicked(0,0,net.minecraft.world.inventory.ClickType.PICKUP,player);h.assertTrue(owner.items.getStackInSlot(0).isEmpty()&&menu.getCarried().getCount()==5&&owner.stored==0,"Remote pickup fee/conservation wrong");menu.clicked(-999,0,net.minecraft.world.inventory.ClickType.PICKUP,player);h.assertTrue(menu.getCarried().getCount()==5,"Remote outside click created a world drop");owner.stored=10;menu.clicked(0,0,net.minecraft.world.inventory.ClickType.PICKUP,player);h.assertTrue(menu.getCarried().isEmpty()&&owner.items.getStackInSlot(0).getCount()==5&&owner.stored==0,"Remote insertion fee wrong");h.assertTrue(menu.quickMoveStack(player,0).isEmpty()&&owner.items.getStackInSlot(0).getCount()==5,"Shift-click bypassed power cost");owner.unlink();h.assertTrue(!menu.stillValid(player),"Unlinked menu retained another node's inventory authority");h.succeed();}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void held_filter_card_templates_persist_without_inventory_duplication(GameTestHelper h){var player=h.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);var card=new ItemStack(BuiltInRegistries.ITEM.get(ResourceLocation.parse("zerog_tweaks:item_filter_card")));player.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,card);var menu=new TransportFilterMenu(1,player.getInventory(),net.minecraft.world.InteractionHand.MAIN_HAND);menu.setCarried(new ItemStack(Items.DIAMOND,9));menu.clicked(0,0,net.minecraft.world.inventory.ClickType.PICKUP,player);h.assertTrue(menu.getCarried().getCount()==9&&menu.templates.getStackInSlot(0).getCount()==1&&menu.quickMoveStack(player,0).isEmpty(),"Card ghost template moved physical items");h.assertTrue(menu.clickMenuButton(player,0),"Card whitelist toggle rejected");var saved=card.get(net.minecraft.core.component.DataComponents.CUSTOM_DATA).copyTag();h.assertTrue(saved.getBoolean("blacklist")&&saved.getCompound("templates").getInt("Size")==9,"Card configuration not saved");var reopened=new TransportFilterMenu(2,player.getInventory(),net.minecraft.world.InteractionHand.MAIN_HAND);h.assertTrue(reopened.templates.getStackInSlot(0).is(Items.DIAMOND),"Held card lost templates on reopen");player.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new ItemStack(Items.STONE));h.assertTrue(!menu.stillValid(player)&&!menu.clickMenuButton(player,1),"Switched-away card retained edit authority");h.succeed();}
    @GameTest(templateNamespace="zerog_tweaks",template="equipment_empty",timeoutTicks=100)
    public static void oversized_network_fails_closed_not_multiple_partial_leaders(GameTestHelper h){var nodes=new java.util.ArrayList<TransportBlockEntity>();for(int i=0;i<257;i++)nodes.add(place(h,new BlockPos(i%5,10+i/25,(i/5)%5),"copper_energy_conduit"));var source=place(h,new BlockPos(-1,10,0),"energy_port");var sink=place(h,new BlockPos(5,10,0),"energy_port");source.stored=10000;nodes.get(0).modes[Direction.WEST.ordinal()]=2;nodes.get(4).modes[Direction.EAST.ordinal()]=1;for(var node:nodes)TransportBlockEntity.tick(h.getLevel(),node.getBlockPos(),node.getBlockState(),node);int buffered=nodes.stream().mapToInt(n->n.stored).sum();h.assertTrue(source.stored==10000&&sink.stored==0&&buffered==0,"Oversized graph became partial full-rate networks");for(int i=0;i<257;i++)place(h,new BlockPos(i%5,10+i/25,(i/5)%5),"copper_fluid_pipe");var pipe=(TransportBlockEntity)h.getBlockEntity(new BlockPos(0,10,0));h.assertTrue(pipe.fluidHandler(null).fill(new FluidStack(net.minecraft.world.level.material.Fluids.WATER,250),IFluidHandler.FluidAction.EXECUTE)==0&&pipe.tank.isEmpty(),"Oversized fluid network accepted unchecked input");h.succeed();}
}
