"""Native source renderer for approved C equipment and A/C botany.

This is source artwork, not a concept crop, resize filter or image recolour.
Reuses named native drawing functions from earlier generators without executing
their registration/model/data writers. Run LAST after those generators.
No registry, geometry, display, animation timing, lang or Java changes.
"""
import argparse, ast, base64, colorsys, hashlib, io, json, math, random, re, sys, uuid, subprocess, tarfile, zipfile
from pathlib import Path
from collections import Counter
from PIL import Image, ImageDraw, ImageFont

P = argparse.ArgumentParser()
P.add_argument('--code', type=Path, required=True)
args = P.parse_args()
BASE = Path(__file__).resolve().parent
DOCS = BASE.parent
RES = args.code / 'src/main/resources'
TEXTURES = RES / 'assets/zerog_tweaks/textures'
sys.path.insert(0, str(DOCS / 'zero-g-tweaks-bundle/generators'))
from data import M
from gear_sets import S
ROWS, TILES, REUSED, MODEL_ROWS = [], [], [], []
RAMPS={
 'moonsteel':['141326','2b2a4a','454a78','6a7bb0','9fb6d8','e6f4ff'],
 'copper':['1e0d0b','4a1f17','83391f','c0622c','eb9a52','ffd9a0'],
 'nullifite':['0b0712','231536','3f2766','6a45a8','a07ee0','e2d4ff'],
 'solvanite':['1f0e05','5a2b0a','a3570f','e09a1c','ffd04a','fff4c0'],
 'cerulite':['06141f','0e3550','14648a','1fa2c4','5fe0f0','dcffff'],
 'leaf':['0a1a1c','14383a','1f5e58','2f8a78','58b894','a8e6c0'],
 'glow':['2a0e4a','5a22a0','9a4ef0','c48cff','e8ccff','ffffff'],
 'rock':['121220','272838','3e4052','5c5f74','85899c','b9bccb'],
 'wood':['1a0e0a','3c2216','5e3a24','875a36','b0824e','dcb27a'],
 'tint_gray':['161616','363636','5a5a5a','868686','b6b6b6','ececec']}
COLOR_RAMPS={tuple(bytes.fromhex(M[n]['pal'][3].lstrip('#'))):n for n in ['moonsteel','nullifite','solvanite','cerulite']}
COLOR_RAMPS.update({(161,175,198):'moonsteel',(174,107,236):'glow',(187,111,239):'glow',(189,114,244):'glow',(182,110,240):'glow',(176,106,237):'glow',(184,111,239):'glow',(101,224,242):'cerulite',(78,72,92):'wood',(88,70,75):'wood',(75,79,106):'rock',(65,161,150):'leaf'})
COLOR_RAMPS.update({(192,98,44):'copper',(45,144,126):'leaf',(125,68,53):'wood',(49,36,37):'wood'})

def git_command(worktree):
    if sys.platform!='win32':return ['git','-C',str(worktree)]
    raw=(worktree/'.git').read_text().strip().removeprefix('gitdir: ')
    if raw.startswith('/mnt/c/'):raw='C:/'+raw[7:]
    return ['C:/Program Files/Git/bin/git.exe','--git-dir='+raw,'--work-tree='+str(worktree)]

def baseline():
    path=BASE/'baseline-head-textures.json'
    if path.exists():return json.loads(path.read_text())
    git=git_command(args.code);commit=subprocess.check_output(git+['rev-parse','HEAD']).decode().strip()
    archive=subprocess.check_output(git+['archive',commit,'src/main/resources/assets/zerog_tweaks/textures'])
    hashes={}
    with tarfile.open(fileobj=io.BytesIO(archive)) as tar:
        for member in tar.getmembers():
            if member.isfile() and member.name.endswith('.png'):
                hashes[member.name.removeprefix('src/main/resources/')]=hashlib.sha256(tar.extractfile(member).read()).hexdigest()
    result={'commit':commit,'meaning':'immutable pre-work code HEAD, not last generated bytes','textures':hashes}
    path.write_text(json.dumps(result,indent=2)+'\n');return result

def functions(path, names, constants=()):
    """Load audited drawing functions only: no top-level asset/data writes."""
    tree = ast.parse(path.read_text())
    selected = [node for node in tree.body if isinstance(node, ast.FunctionDef)
                and node.name in names or isinstance(node, ast.Assign)
                and any(isinstance(t, ast.Name) and t.id in constants for t in node.targets)]
    ns = dict(Image=Image, ImageDraw=ImageDraw, colorsys=colorsys, math=math,
              random=random, hashlib=hashlib, themes=['moon','mars','cerulon','skarn','eidolon','solvane'])
    exec(compile(ast.Module(body=selected, type_ignores=[]), str(path), 'exec'), ns)
    REUSED.append({'generator':path.relative_to(DOCS.parent).as_posix(), 'sha256':digest(path), 'functions':names})
    return ns

def digest(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def colour(value): return tuple(bytes.fromhex(value.lstrip('#')))
def shade(c, level=1):
    if tuple(c[:3]) in COLOR_RAMPS:
        ramp=RAMPS[COLOR_RAMPS[tuple(c[:3])]]
        index=0 if level<.43 else 1 if level<.7 else 2 if level<.91 else 3 if level<1.15 else 4 if level<1.4 else 5
        return tuple(bytes.fromhex(ramp[index]))+(255,)
    target = (44,33,81) if level < 1 else (255,241,211)
    mix = min(.27, abs(level-1)*.43)
    return tuple(round(min(255,max(0,v*level))*(1-mix)+t*mix) for v,t in zip(c,target))+(255,)
def blank(size=(32,32)): return Image.new('RGBA',size)
def crystal(d,x,y,c,scale=3):
    d.polygon([(x,y-scale),(x+scale,y),(x+1,y+scale),(x-scale,y+1)],fill=shade(c,.55))
    d.polygon([(x,y-scale+1),(x+scale-1,y),(x,y+1),(x-scale+1,y)],fill=shade(c,1.15))
    d.line((x,y-scale+1,x-1,y),fill=shade(c,1.65))
    d.point((x+1,y+1),fill=shade(c,.78))

def save(key, im, category, contract=None, allow_new=False):
    relative = 'assets/zerog_tweaks/textures/'+key+'.png'
    dst = RES / relative
    if not dst.exists() and not allow_new: return False
    before = digest(dst) if dst.exists() else None
    src = BASE/'source'/relative
    src.parent.mkdir(parents=True,exist_ok=True)
    im.save(src)
    payload = src.read_bytes()
    targets = [dst]
    # Enumerate every existing resource layer, rather than assuming one override.
    for pack in (RES/'resourcepacks').glob('*'):
        if (pack/relative).exists() or key.endswith('_glowmask') and (pack/relative.replace('_glowmask.png','.png')).exists(): targets.append(pack/relative)
    for target in targets: target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(payload)
    meta = dst.with_suffix('.png.mcmeta')
    if meta.exists():
        src.with_suffix('.png.mcmeta').write_bytes(meta.read_bytes())
        for target in targets[1:]: target.with_suffix('.png.mcmeta').write_bytes(meta.read_bytes())
    ROWS.append({'path':relative,'category':category,'sha256':digest(src), 'rerun_previous_sha256':before,
                 'size':list(im.size),'alpha_bounds':im.getbbox(),'contract':contract,
                 'layers':[t.relative_to(RES).as_posix() for t in targets]})
    TILES.append((key, im.crop((0,0,im.width,min(im.width,im.height)))))
    return True

def trim_icons():
    """One native 32px trim template per piece; thirty palette variants, not 2400 sprites."""
    slots=['helmet','chestplate','leggings','boots'];audit=[];built=set()
    client=Path('C:/Users/jakem/.gradle/caches/neoformruntime/artifacts/minecraft_1.21.1_client.jar') if sys.platform=='win32' else Path('/mnt/c/Users/jakem/.gradle/caches/neoformruntime/artifacts/minecraft_1.21.1_client.jar')
    jar=zipfile.ZipFile(client)
    for name in S:
        for slot in slots:
            base=Image.open(TEXTURES/f'item/{name}_{slot}.png').convert('RGBA')
            parent=json.loads((RES/f'assets/zerog_tweaks/models/item/{name}_{slot}.json').read_text())
            for override in parent.get('overrides',[]):
                ref=override['model'];relative='assets/zerog_tweaks/models/'+ref.split(':',1)[1]+'.json'
                old=json.loads((RES/relative).read_text())
                mat=Path(ref.split(':',1)[1]).name.removeprefix(name+'_'+slot+'_').removesuffix('_trim')
                material='zerog_'+mat if mat in S else mat
                key=slot+'_'+material
                if key not in built:
                    mat=material.removeprefix('zerog_')
                    palette_path=TEXTURES/f'trims/color_palettes/{mat}.png'
                    pal=Image.open(palette_path).convert('RGBA') if palette_path.exists() else Image.open(io.BytesIO(jar.read(f'assets/minecraft/textures/trims/color_palettes/{mat}.png'))).convert('RGBA')
                    colours=list(pal.getdata());hi,mid,lo=colours[0],colours[len(colours)//3],colours[-2]
                    overlay=blank();d=ImageDraw.Draw(overlay)
                    paths={'helmet':[[(8,12),(22,12)],[(7,18),(7,23)],[(24,18),(24,22)]],
                           'chestplate':[[(5,10),(9,10)],[(23,10),(27,11)],[(12,23),(17,26),(21,23)]],
                           'leggings':[[(9,10),(22,10)],[(8,21),(11,21)],[(20,21),(23,21)]],
                           'boots':[[(7,19),(11,19)],[(21,19),(25,19)],[(6,24),(12,24)],[(20,24),(26,24)]]}[slot]
                    for points in paths:
                        d.line(points,fill=mid,width=2);d.line([(x,y-1) for x,y in points],fill=hi)
                        d.line([(x,y+1) for x,y in points],fill=lo)
                    for y in range(32):
                        for x in range(32):
                            if not base.getpixel((x,y))[3]:overlay.putpixel((x,y),(0,0,0,0))
                    save('item/armor_trims/'+key,overlay,'native_trim_overlays',{'palette_id':material,'matching_base_size':32,'alpha_clamped_to_base':True},allow_new=True)
                    built.add(key)
                new={'parent':'minecraft:item/generated','textures':{'layer0':f'zerog_tweaks:item/{name}_{slot}','layer1':f'zerog_tweaks:item/armor_trims/{key}'}}
                artifact(relative,new,'trim_item_override_models')
                audit.append({'model':relative,'base':new['textures']['layer0'],'overlay':new['textures']['layer1'],'original_palette_id':material,'pixels':32})
    jar.close();(BASE/'trim-alignment-audit.json').write_text(json.dumps({'variants':len(audit),'shared_native_overlays':len(built),'old_overlay_contract':'16px vanilla shapes do not align with approved 32px armour outlines','models':audit},indent=2)+'\n')

def artifact(relative,obj,category):
    payload=(json.dumps(obj,indent=2)+'\n').encode()
    src=BASE/'source'/relative;src.parent.mkdir(parents=True,exist_ok=True);src.write_bytes(payload)
    path=RES/relative;path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(payload)
    for pack in (RES/'resourcepacks').glob('*'):
        if (pack/relative).exists() or relative.endswith('.png.mcmeta') and (pack/relative.removesuffix('.mcmeta')).exists():
            (pack/relative).write_bytes(payload)
    MODEL_ROWS.append({'path':relative,'category':category,'sha256':digest(src)})

def anchor(group=False):
    im=blank();d=ImageDraw.Draw(im);c=(153,174,204);acc=(184,111,239)
    d.polygon([(14,3),(19,5),(19,18),(24,20),(26,17),(28,20),(25,26),(19,29),(13,29),(6,25),(4,20),(7,17),(9,20),(13,18)],fill=shade(c,.4))
    d.line([(16,5),(16,23)],fill=shade(c,1.18),width=3)
    d.line([(6,20),(10,25),(16,27),(23,24),(26,20)],fill=shade(c,1.34),width=2)
    d.line((11,13,22,13),fill=shade(c,1.15),width=2)
    crystal(d,16,7,acc,3)
    if group:
        for x,y in [(8,8),(24,8)]:
            d.ellipse((x-2,y-2,x+2,y+2),fill=shade((99,224,241),1.1));d.line((x,y+3,16,16),fill=shade(acc,.9))
    return im

def planetary_kelp():
    greens=[(104,160,161),(110,146,94),(57,165,150),(103,135,105),(115,168,190),(150,165,88)]
    accents=[(185,128,231),(235,148,90),(146,126,232),(242,160,83),(181,127,226),(229,143,211)]
    lang={}
    for n,theme in enumerate(['moon','mars','cerulon','skarn','eidolon','solvane']):
        c,accent=greens[n],accents[n]
        for body in [False,True]:
            id=theme+'_kelp'+('_plant' if body else '')
            im=vines(c,accent,False,kelp=True,tip=not body);d=ImageDraw.Draw(im)
            for x,y in [(15,7),(17,17),(14,26)]:d.line((x,y,x+1,y+2),fill=shade(accent,1.32))
            frames=blank((32,128))
            for f in range(4):
                frame=im.copy();fd=ImageDraw.Draw(frame)
                for x,y in [(15,7),(17,17),(14,26)]:fd.point((x,y),fill=shade(accent,[1.0,1.25,1.5,1.25][f]))
                frames.paste(frame,(0,f*32))
            save('block/'+id,frames,'planetary_kelp',{'frame_count':4,'frame_size':32},allow_new=True)
            meta={'animation':{'frametime':6,'interpolate':True}}
            artifact('assets/zerog_tweaks/textures/block/'+id+'.png.mcmeta',meta,'plant_animation_metadata')
            artifact('assets/zerog_tweaks/models/block/'+id+'.json',{'parent':'minecraft:block/cross','textures':{'cross':'zerog_tweaks:block/'+id},'render_type':'minecraft:cutout'},'planetary_kelp_models')
            artifact('assets/zerog_tweaks/blockstates/'+id+'.json',{'variants':{'':{'model':'zerog_tweaks:block/'+id}}},'planetary_kelp_blockstates')
            artifact('data/zerog_tweaks/loot_table/blocks/'+id+'.json',{'type':'minecraft:block','pools':[{'rolls':1,'bonus_rolls':0,'conditions':[{'condition':'minecraft:survives_explosion'}],'entries':[{'type':'minecraft:item','name':'zerog_tweaks:'+theme+'_kelp'}]}],'random_sequence':'zerog_tweaks:blocks/'+id},'planetary_kelp_loot')
            lang['block.zerog_tweaks.'+id]=theme.title()+' '+('Kelp Plant' if body else 'Kelp')
        head=theme+'_kelp'
        save('item/'+head,vines(c,accent,False,kelp=True,tip=True),'planetary_kelp_items',allow_new=True)
        artifact('assets/zerog_tweaks/models/item/'+head+'.json',{'parent':'minecraft:item/generated','textures':{'layer0':'zerog_tweaks:item/'+head}},'planetary_kelp_item_models')
        # Vanilla-like cooking, stable output id: no invented six food families.
        artifact('data/zerog_tweaks/recipe/'+head+'_drying.json',{'type':'minecraft:smelting','category':'food','ingredient':{'item':'zerog_tweaks:'+head},'result':{'id':'minecraft:dried_kelp'},'experience':.1,'cookingtime':200},'planetary_kelp_recipes')
        artifact('data/zerog_tweaks/recipe/'+head+'_smoking.json',{'type':'minecraft:smoking','category':'food','ingredient':{'item':'zerog_tweaks:'+head},'result':{'id':'minecraft:dried_kelp'},'experience':.1,'cookingtime':100},'planetary_kelp_recipes')
    (BASE/'planetary-kelp-lang-fragment.json').write_text(json.dumps(lang,indent=2)+'\n')

def transport():
    path=BASE/'transport-source/transport.py'
    names=['hx','sh','mix','tex','P','pipe_texture','connector_texture','casing','port_face','cell_side','cell_top','gauge','null_link_frames','item_icon','face','pipe_models','connector_models','port_models','cell_models','misc_models']
    tr=functions(path,names,['NS','TIERS','FE','MB','ITEMS','CELL','TYPES','MODES','MODE_COL','TYPE_COL','HOT_FLUIDS','TEX','MODELS','STATES','GLYPH'])
    # Preserve the supplied narrow-pipe UV dimensions and semantic mode colours.
    tr['sh']=lambda c,k,a=None:shade(c[:3],k)[:3]+((c[3] if len(c)>3 else 255) if a is None else a,)
    for kind in tr['TYPES']:
        for tier in range(6):tr['pipe_models'](kind,tier)
    for name in ['connector_models','port_models','cell_models','misc_models']:tr[name]()
    for key,im in tr['TEX'].items():
        save(key,im,'transport_contract_assets',{'verified_uv_size':16,'native_source':str(path.relative_to(DOCS.parent))},allow_new=True)
    meta=TEXTURES/'block/transport/null_link.png.mcmeta';meta.write_text(json.dumps({'animation':{'frametime':3,'interpolate':True}})+'\n')
    (BASE/'source/assets/zerog_tweaks/textures/block/transport/null_link.png.mcmeta').write_bytes(meta.read_bytes())
    for key,obj in tr['MODELS'].items():
        if key.startswith('item/'):
            relative='assets/zerog_tweaks/models/'+key+'.json'
        else:relative='assets/zerog_tweaks/models/'+key+'.json'
        artifact(relative,obj,'transport_models')
    for key,obj in tr['STATES'].items():artifact('assets/zerog_tweaks/blockstates/'+key+'.json',obj,'transport_blockstates')

def equipment(c,accent,kind,cfg):
    im=blank();d=ImageDraw.Draw(im);dark=shade(c,.34)
    if kind in ['sword','pickaxe','axe','shovel','hoe']:
        # Deliberately authored diagonal grip; no resampling/rotation artifacts.
        grip=(88,70,75);d.line([(5,27),(19,13)],fill=shade(grip,.43),width=5)
        d.line([(5,26),(19,12)],fill=shade(grip,.99),width=3)
        for x,y in [(7,24),(10,21),(13,18)]:d.line((x-1,y-1,x+1,y+1),fill=shade(grip,.57))
        d.line([(5,26),(18,13)],fill=shade(c,1.08))
        crystal(d,5,27,accent,2)
        if kind=='sword':
            wide=cfg[kind].get('gw',3)>2
            d.polygon([(12,19),(15,16),(24,5),(29,2),(29,7),(18,20),(15,22)],fill=dark)
            d.polygon([(14,19),(17,16),(25,6),(28,4),(27,8),(18,19)],fill=shade(c,1.15))
            d.line([(15,18),(25,6),(28,4)],fill=shade(c,1.65))
            d.line([(18,18),(27,7)],fill=shade(c,.71))
            d.line([(18,16),(26,7)],fill=shade(accent,.78))
            d.line([(19,15),(23,10)],fill=shade(accent,1.35))
            d.line([(10,15),(18,23)],fill=dark,width=4 if wide else 3)
            d.line([(10,14),(18,22)],fill=shade(c,1.1),width=2)
            crystal(d,15,18,accent,2)
        elif kind=='pickaxe':
            d.polygon([(5,11),(10,6),(18,4),(24,6),(28,10),(29,19),(25,16),(23,12),(17,9),(10,10)],fill=dark)
            d.polygon([(7,10),(12,7),(18,6),(23,8),(26,12),(27,16),(24,11),(17,8),(11,9)],fill=shade(c,1.05))
            d.line([(8,9),(13,6),(18,5),(23,7),(26,11)],fill=shade(c,1.55))
            d.line([(18,7),(22,9),(24,12)],fill=shade(accent,1.12),width=2)
            crystal(d,19,9,accent,3)
        elif kind=='axe':
            d.polygon([(11,5),(20,4),(28,8),(28,16),(24,20),(18,17),(18,12),(11,10)],fill=dark)
            d.polygon([(12,6),(20,6),(26,9),(26,15),(23,18),(20,15),(20,10),(12,9)],fill=shade(c,1.07))
            d.line([(12,5),(20,5),(27,9),(27,15),(24,18)],fill=shade(c,1.55))
            d.polygon([(22,7),(26,9),(26,15),(24,17),(23,13)],fill=shade(c,.66))
            d.polygon([(13,7),(19,7),(22,9),(21,11),(16,9)],fill=shade(c,1.3))
            d.line([(25,10),(25,14),(23,16)],fill=shade(c,1.48))
            d.line([(21,8),(24,11),(24,15)],fill=shade(accent,.91))
            crystal(d,18,10,accent,2)
        elif kind=='shovel':
            d.polygon([(16,10),(23,3),(29,4),(29,11),(22,17),(18,15)],fill=dark)
            d.polygon([(17,10),(24,4),(28,5),(27,11),(22,15)],fill=shade(c,1.08))
            d.line([(18,10),(24,4),(28,5)],fill=shade(c,1.55))
            d.line((20,12,25,7),fill=shade(accent,1.15))
        else:
            d.polygon([(10,5),(19,5),(25,9),(27,16),(24,17),(21,12),(17,10),(10,9)],fill=dark)
            d.line([(11,6),(18,6),(23,10),(25,15)],fill=shade(c,1.2),width=2)
            d.line([(11,5),(18,5),(23,9)],fill=shade(c,1.55))
            crystal(d,19,9,accent,2)
    else:
        if kind=='helmet':
            d.polygon([(8,5),(21,4),(27,10),(27,25),(23,27),(21,16),(10,16),(9,27),(5,25),(4,12)],fill=dark)
            d.polygon([(8,7),(20,6),(24,10),(23,14),(8,14),(6,12)],fill=shade(c,1.09))
            d.line([(8,6),(16,5),(21,6),(24,9)],fill=shade(c,1.6),width=2)
            d.line([(13,6),(15,10),(14,14)],fill=shade(c,.65))
            d.polygon([(8,8),(11,7),(13,10),(12,13),(8,13),(7,11)],fill=shade(c,.86))
            d.polygon([(17,7),(20,7),(23,10),(21,13),(17,13),(16,10)],fill=shade(c,.84))
            d.line([(9,7),(12,7),(14,10),(13,13)],fill=shade(c,1.36))
            d.line([(17,7),(21,9),(22,12)],fill=shade(c,1.5))
            d.line((10,13,20,13),fill=shade(c,.49))
            d.polygon([(6,15),(10,16),(8,25),(6,24)],fill=shade(c,.87))
            d.polygon([(23,16),(26,13),(25,24),(23,25)],fill=shade(c,.72))
            d.line((7,17,7,23),fill=shade(c,1.45));d.line((24,17,24,21),fill=shade(accent,1.21))
        elif kind=='chestplate':
            d.polygon([(5,5),(10,4),(12,9),(19,9),(22,4),(27,5),(30,12),(25,16),(23,14),(24,25),(18,29),(10,27),(8,15),(5,16),(2,12)],fill=dark)
            for shape in [[(4,8),(9,6),(11,12),(6,14),(3,11)],[(22,6),(27,8),(29,11),(25,14),(20,12)],[(10,12),(16,15),(21,12),(22,24),(17,27),(11,24)]]:
                d.polygon(shape,fill=shade(c,1.04))
            d.polygon([(4,10),(8,9),(10,12),(6,14)],fill=shade(c,.66))
            d.polygon([(22,10),(27,10),(28,12),(25,14),(21,12)],fill=shade(c,.69))
            d.polygon([(11,15),(14,17),(14,23),(17,27),(12,25)],fill=shade(c,.69))
            d.polygon([(20,15),(18,18),(18,23),(21,24)],fill=shade(c,.72))
            d.line([(12,15),(14,18),(14,22)],fill=shade(c,1.25))
            d.line([(20,16),(19,19),(19,22)],fill=shade(c,1.3))
            d.line([(5,7),(9,6),(11,10)],fill=shade(c,1.6))
            d.line([(22,6),(27,8),(28,10)],fill=shade(c,1.43))
            d.line([(10,12),(16,16),(21,12)],fill=shade(c,1.5),width=2)
            d.line([(11,18),(14,21),(13,24)],fill=shade(c,.64))
            d.line([(22,19),(19,22),(19,25)],fill=shade(c,.62))
            d.line((16,17,17,24),fill=shade(accent,1.2),width=2)
            crystal(d,16,18,accent,3)
        elif kind=='leggings':
            d.polygon([(6,5),(25,5),(26,12),(24,27),(18,28),(17,15),(14,15),(13,28),(6,27)],fill=dark)
            d.rectangle((8,7,23,11),fill=shade(c,1.13));d.line((8,7,23,7),fill=shade(c,1.6))
            for x in [8,20]:
                d.rectangle((x,12,x+3,25),fill=shade(c,.91))
                d.line((x+3,12,x+3,25),fill=shade(c,.57))
                d.polygon([(x-1,18),(x+2,17),(x+4,19),(x+3,22),(x,22)],fill=shade(c,1.22))
                d.line((x,13,x,17),fill=shade(c,1.55));d.point((x+2,20),fill=shade(accent,1.4))
            crystal(d,16,9,accent,2)
        else:
            for x in [5,19]:
                d.polygon([(x+1,6),(x+7,6),(x+7,22),(x+9,24),(x+9,27),(x-1,27),(x-1,23),(x+1,21)],fill=dark)
                d.rectangle((x+2,8,x+6,20),fill=shade(c,.9))
                d.polygon([(x+1,22),(x+6,22),(x+8,24),(x+7,25),(x,25)],fill=shade(c,1.14))
                d.line((x+2,8,x+6,8),fill=shade(c,1.5));d.line((x+3,10,x+3,14),fill=shade(accent,1.1))
                d.line((x,26,x+8,26),fill=shade(c,.63))
    return im

def metal_bar(c,accent):
    im=blank();d=ImageDraw.Draw(im)
    d.polygon([(3,13),(11,6),(26,8),(29,13),(27,23),(9,27),(3,21)],fill=shade(c,.37))
    d.polygon([(4,13),(11,8),(25,9),(27,13),(21,18),(9,20)],fill=shade(c,1.18))
    d.polygon([(4,15),(8,21),(8,25),(4,20)],fill=shade(c,.65))
    d.polygon([(10,21),(22,19),(27,15),(25,22),(10,25)],fill=shade(c,.9))
    d.line([(5,13),(12,8),(24,9)],fill=shade(c,1.63))
    d.line([(10,22),(21,20)],fill=shade(c,1.06))
    for x,y in [(15,11),(24,20),(12,23)]:crystal(d,x,y,accent,1)
    return im

def tool_swatch_atlas():
    """Moonsteel 64px contract: twelve native 16px material faces, fixed cells."""
    im=blank((64,64));d=ImageDraw.Draw(im);c=(161,175,198);acc=(174,107,236)
    roles=['light','mid','dark','edge','grip','wrap','glow','gem','plate','trim','socket','core']
    for i,role in enumerate(roles):
        x0,y0=(i%4)*16,(i//4)*16
        for y in range(16):
            for x in range(16):
                if role in ['glow','gem','core']:
                    dist=(abs(x-7.5)+abs(y-7.5))/15 if role!='glow' else abs(x-7.5)/7.5
                    col=shade((101,224,242) if role=='glow' else acc,1.65 if dist<.22 else 1.1 if dist<.6 else .64)
                elif role in ['grip','wrap']:
                    col=shade((78,72,92),.52 if (x+y)%6<2 else 1.1)
                else:
                    level={'light':1.12,'mid':.91,'dark':.59,'edge':1.25,'plate':.84,'trim':.5,'socket':.83}[role]
                    level+=.22 if x==0 or y==0 else -.23 if x==15 or y==15 else .1 if x<5 else -.09 if x>11 else 0
                    col=shade(c,level)
                im.putpixel((x0+x,y0+y),col)
        if role in ['mid','light','plate']:
            d.line((x0+3,y0+4,x0+12,y0+4),fill=shade(c,.68));d.line((x0+3,y0+5,x0+11,y0+5),fill=shade(c,1.18))
        if role in ['socket','plate']:
            for x,y in [(2,2),(13,2),(2,13),(13,13)]:d.point((x0+x,y0+y),fill=shade(c,1.57))
    return im

def raw_chunk(c,accent):
    im=blank();d=ImageDraw.Draw(im);rock=(75,79,106)
    for x,y,r in [(10,19,7),(21,14,8),(22,25,4)]:
        d.polygon([(x-r,y),(x-3,y-r),(x+3,y-r+1),(x+r,y+2),(x+2,y+r),(x-r+1,y+4)],fill=shade(rock,.51))
        d.polygon([(x-r+1,y-1),(x-3,y-r+1),(x+3,y-r+2),(x+1,y+1)],fill=shade(c,.92))
        d.line([(x-r+2,y-1),(x-3,y-r+2)],fill=shade(c,1.5))
    for x,y,pal in [(9,20,accent),(20,10,(97,226,241)),(22,22,accent)]:crystal(d,x,y,pal,4)
    return im

def fuel_chunk(c,accent):
    im=blank();d=ImageDraw.Draw(im)
    for x,y,r in [(10,18,7),(21,13,7),(20,25,4)]:
        d.polygon([(x-r,y-2),(x-2,y-r),(x+r-2,y-r+2),(x+r,y+3),(x+2,y+r),(x-r,y+4)],fill=shade(c,.4))
        d.polygon([(x-r+1,y-2),(x-2,y-r+1),(x+r-3,y-r+3),(x+1,y+1)],fill=shade(c,1.09))
        d.line([(x-r+2,y-2),(x-2,y-r+2)],fill=shade(c,1.4))
        d.line([(x-2,y+4),(x+1,y+1),(x+4,y+2)],fill=shade(accent,.97))
        d.point((x+1,y+1),fill=shade(accent,1.5))
    return im

def wooden_door(c,upper=False):
    im=blank();d=ImageDraw.Draw(im)
    d.rectangle((0,0,31,31),fill=shade(c,.87))
    for x in [2,9,16,23,29]:
        d.line((x,0,x,31),fill=shade(c,.59));d.line((x+1,0,x+1,31),fill=shade(c,1.24))
    for y in [2,27]:
        d.rectangle((2,y,29,y+2),fill=shade(c,.51));d.line((3,y,28,y),fill=shade(c,1.35))
    if upper:
        for x in [6,18]:d.rectangle((x,8,x+7,21),fill=(0,0,0,0))
        d.line((16,7,16,22),fill=shade(c,1.15),width=2)
    else:
        d.rectangle((6,8,25,22),outline=shade(c,.61));d.line((7,8,24,8),fill=shade(c,1.21))
        d.rectangle((25,8,27,11),fill=shade((141,163,191),.67));d.point((25,8),fill=shade((141,163,191),1.27))
    return im

def atlas(geo, original, c, accent, glow_original=None, emit_inlays=False):
    """Repaint cube face nets at exact authored UVs; preserve open alpha masks."""
    im=blank(original.size);glow=blank(original.size);d=ImageDraw.Draw(im)
    bounds=[]
    for bone in geo['minecraft:geometry'][0]['bones']:
        for cube in bone.get('cubes',[]):
            uv=cube.get('uv');size=cube['size'];w,h,z=[max(1,math.ceil(v)) for v in size]
            if not isinstance(uv,list):continue # explicit face atlases are reviewed separately
            u,v=uv
            for face,(x,y,fw,fh) in enumerate([(u+z,v,w,z),(u+z+w,v,w,z),(u,v+z,z,h),(u+z,v+z,w,h),(u+z+w,v+z,z,h),(u+2*z+w,v+z,w,h)]):
                x,y=int(x),int(y); bounds.append([x,y,x+fw,y+fh])
                assert x>=0 and y>=0 and x+fw<=im.width and y+fh<=im.height,(bone['name'],uv,size,im.size)
                for yy in range(fh):
                    for xx in range(fw):
                        a=original.getpixel((x+xx,y+yy))[3]
                        if not a:continue
                        k=1.38 if yy==0 else .49 if yy==fh-1 else 1.09 if xx==0 else .64 if xx==fw-1 else [.82,1.04,1.18][min(2,xx*3//fw)]
                        col=shade(c,k)
                        # Layer seams and plate bevels, no per-pixel white noise.
                        if fh>=6 and yy in [fh//2,fh//2+1]:col=shade(c,.59 if yy==fh//2 else 1.16)
                        if fw>=5 and face==3 and 'Head' not in bone['name'] and xx==fw//2 and 2<=yy<fh-2:
                            col=shade(accent,1.12 if yy%4 else 1.5)
                            if emit_inlays:glow.putpixel((x+xx,y+yy),col[:3]+(a,))
                        im.putpixel((x+xx,y+yy),col[:3]+(a,))
                        if glow_original and glow_original.getpixel((x+xx,y+yy))[3]:
                            col=shade(accent,1.14 if xx%3 else 1.5);im.putpixel((x+xx,y+yy),col[:3]+(a,));glow.putpixel((x+xx,y+yy),col)
    return im,glow,bounds

def worn_facets(coverage,c,accent,layer):
    """Original 128x64 plate artwork on normalized vanilla/netherite UV coverage.

    The template's alpha footprint alone is doubled, never its old flat artwork.
    Each face is painted at native output density with directional plate facets,
    narrow bevels, a mirrored breastplate chevron, and recessed energy sockets.
    """
    im=blank((128,64));d=ImageDraw.Draw(im);mask=Image.new('L',im.size)
    md=ImageDraw.Draw(mask)
    for y,xs in enumerate(coverage['rows']):
        for x in xs:md.rectangle((x*2,y*2,x*2+1,y*2+1),fill=255)
    bounds=[];cyan=(101,224,242)
    bones=[('Head',0,0,8,8,8),('Body',16,16,8,12,4),('Arm',40,16,4,12,4),('Leg',0,16,4,12,4)]
    for name,u,v,w,h,z in bones:
        faces=[(u+z,v,w,z),(u+z+w,v,w,z),(u,v+z,z,h),(u+z,v+z,w,h),(u+z+w,v+z,z,h),(u+2*z+w,v+z,w,h)]
        for face,(x,y,fw,fh) in enumerate(faces):
            x,y,fw,fh=x*2,y*2,fw*2,fh*2;bounds.append([x,y,x+fw,y+fh])
            # Diagonal broad planes, not vertical stripes or repetitive banding.
            d.rectangle((x,y,x+fw-1,y+fh-1),fill=shade(c,.38))
            d.polygon([(x+1,y+1),(x+fw-2,y+1),(x+fw-2,y+fh-3),(x+fw//2,y+fh-2),(x+1,y+fh-4)],fill=shade(c,.86))
            d.polygon([(x+1,y+1),(x+fw-2,y+1),(x+fw//2,y+fh//2),(x+1,y+fh-4)],fill=shade(c,1.21 if face<2 else 1.08))
            d.polygon([(x+fw-2,y+1),(x+fw-2,y+fh-3),(x+fw//2,y+fh-2),(x+fw//2,y+fh//2)],fill=shade(c,.64))
            d.line([(x+1,y+fh-3),(x+fw//2,y+fh-1),(x+fw-2,y+fh-3)],fill=shade(c,.52))
            d.line([(x+1,y+fh-4),(x+fw//2,y+fh-2),(x+fw-2,y+fh-4)],fill=shade(c,1.24))
            d.line([(x+1,y+2),(x+1,y+1),(x+fw-3,y+1)],fill=shade(c,1.65))
            if fw>=8 and fh>=8:
                # An inset seam gives the edge a physical lip, not a black outline.
                d.line((x+2,y+3,x+fw-3,y+3),fill=shade(c,.59))
                d.line((x+3,y+4,x+fw-4,y+4),fill=shade(c,1.34))
                for px,py in [(x+2,y+2),(x+fw-3,y+2),(x+2,y+fh-4),(x+fw-3,y+fh-4)]:
                    d.point((px,py),fill=shade(c,1.52))
            if name=='Body' and face==3 and layer==1:
                cx=x+fw//2;top=y+3;mid=y+fh//2;low=y+fh-4
                for sign in [-1,1]:
                    path=[(cx+sign*(fw//2-2),top),(cx+sign*2,mid),(cx,low)]
                    d.line(path,fill=shade(c,.39),width=4)
                    d.line([(px,py-1) for px,py in path],fill=shade(c,1.44),width=3)
                    d.line(path,fill=shade(cyan,.98),width=1)
                crystal(d,cx,mid+1,accent,3)
                d.point((cx-1,mid),fill=shade(cyan,1.65))
            elif face==3:
                # Short, supported inlays on visor rims, cuffs, kneepads and greaves.
                iy=y+max(4,fh//3);ix=x+fw//2
                d.line((ix,iy,ix,iy+max(1,fh//5)),fill=shade(c,.38),width=3)
                d.line((ix,iy,ix,iy+max(1,fh//5)),fill=shade(accent,1.15))
                d.point((ix,iy),fill=shade(cyan,1.6))
                if name=='Head':
                    d.line([(x+2,y+2),(x+fw//2,y+5),(x+fw-3,y+2)],fill=shade(c,1.55))
                    d.line([(x+3,y+3),(x+fw//2,y+6),(x+fw-4,y+3)],fill=shade(accent,1.08))
    im.putalpha(mask)
    return im,bounds

def native_leaf(d,x,y,spread,c,right=True):
    side=1 if right else -1
    pts=[(x,y),(x+side*spread,y-6),(x+side*(spread+2),y-3),(x+side*2,y+1)]
    d.polygon(pts,fill=shade(c,.58));d.polygon([(x+side,y-1),(x+side*spread,y-5),(x+side*(spread+1),y-3),(x+side*3,y)],fill=shade(c,1.03))
    d.line([(x,y),(x+side*(spread-1),y-3)],fill=shade(c,1.37))
def native_bud(d,x,y,c,size=3,kind='round'):
    if kind=='pod':
        d.polygon([(x-2,y),(x+2,y-1),(x+3,y+size*3-2),(x,y+size*3+1),(x-2,y+size*3-1)],fill=shade(c,.49))
        for yy in range(y+1,y+size*3,3):
            d.ellipse((x-1,yy,x+1,yy+2),fill=shade(c,1.13));d.point((x-1,yy),fill=shade(c,1.55))
    elif kind=='chili':
        d.polygon([(x-2,y),(x+3,y),(x+2,y+6),(x-2,y+10),(x,y+5)],fill=shade(c,.78));d.line((x,y+1,x,y+5),fill=shade(c,1.5))
    else:
        d.ellipse((x-size,y-size,x+size,y+size+1),fill=shade(c,.5))
        d.ellipse((x-size+1,y-size,x+size-1,y+size-1),fill=shade(c,1.07))
        d.line((x-1,y-size+1,x-1,y),fill=shade(c,1.45));d.point((x+1,y+1),fill=shade(c,.76))

def native_crop(theme,id,age):
    """Seven anatomical crop silhouettes, not one recoloured fern template.

    Native 32px grid. Stage 0/1 establish leaves, stage 2 buds/young fruit,
    stage 3 the harvest anatomy. Fruit colours match the approved food sprites.
    The stakes below are pictured plant stems, not an added gameplay requirement.
    """
    greens=[(99,166,155),(76,156,120),(65,161,150),(103,146,118),(100,164,184),(153,167,90)]
    fruits=[(172,128,235),(240,141,81),(239,129,174),(245,147,68),(245,180,102),(213,128,211)]
    i=['moon','mars','cerulon','skarn','eidolon','solvane'].index(theme)
    green,fruit=greens[i],fruits[i];im=blank();d=ImageDraw.Draw(im)
    immature=tuple(round(v*.72+g*.28) for v,g in zip(fruit,green))
    ripe=fruit if age==3 else immature
    h=[6,12,21,28][age];top=31-h
    def stem(points,width=2):
        d.line(points,fill=shade(green,.48),width=width)
        d.line([(x-1,y) for x,y in points],fill=shade(green,1.12))
    def broad(x,y,w,h):
        pts=[(x,y+h),(x-w,y+2),(x-w+2,y-h),(x,y-h-2),(x+w,y-h),(x+w+1,y+2)]
        d.polygon(pts,fill=shade(green,.58))
        d.polygon([(x,y+h-1),(x-w+1,y+1),(x-w+3,y-h+1),(x,y-h),(x+w-1,y-h+1),(x+w-1,y+1)],fill=shade(green,1.01))
        d.line((x-1,y-h+1,x-1,y+h-2),fill=shade(green,1.35))
    if any(s in id for s in ['melon','pumpkin','squash']):
        # Creeping ground vine, paired broad lobes, an offset curling tendril.
        stem([(3,30),(9,27),(16,29),(22,25),(29,27)],2)
        for x,y in [(9,24),(18,24),(25,23)][:age+1]:broad(x,y,2+age//2,2+age//2)
        if age>0:d.line([(22,25),(25,20),(29,20),(29,23),(27,23)],fill=shade(green,1.34))
        if age>1:native_bud(d,6,25,ripe,2)
    elif any(s in id for s in ['pea','bean']):
        # Thin alternating climbing stem; conspicuously long dangling pods.
        stem([(15,31),(16,top+4),(15,top)],2)
        for j in range(age+1):
            y=28-j*6;native_leaf(d,16,y,3,green,j%2==0)
        if age>0:d.line([(15,top+4),(19,top+2),(22,top+3),(22,top+6),(20,top+6)],fill=shade(green,1.35))
        if age>1:
            for x,y in [(10,14),(21,17)] if age==3 else [(21,19)]:
                d.line((16,y-2,x,y),fill=shade(green,.82));native_bud(d,x,y,ripe,3,'pod')
    elif any(s in id for s in ['carrot','turnip','radish','beet','onion','garlic','parsnip','tuber','sunroot']):
        # Low leaf rosette; no tall fern trunk. Root shoulders emerge at maturity.
        reach=[4,7,11,14][age]
        for sign in [-1,1]:
            stem([(16,30),(16+sign*reach,30-reach//2),(16+sign*(reach-1),27-reach//2)],2)
            native_leaf(d,16+sign*3,29,reach-2,green,sign==1)
        broad(16,28-reach//2,2+age//2,2+age)
        if age>1:
            if 'carrot' in id or 'parsnip' in id:
                d.polygon([(12,27),(20,27),(18,31),(15,31)],fill=shade(ripe,.74));d.line((13,28,18,28),fill=shade(ripe,1.36))
            else:
                d.ellipse((12,26,20,33),fill=shade(ripe,.58));d.ellipse((13,26,19,30),fill=shade(ripe,1.05));d.line((14,27,14,29),fill=shade(ripe,1.42))
    elif 'asparagus' in id:
        # Separate straight spears with tightly nested diamond scales at the tips.
        for j,x in enumerate([10,16,22][:age+1]):
            y=top+([4,0,6][j] if age>0 else 0);stem([(x,31),(x,y+3)],3)
            d.polygon([(x-2,y+4),(x-2,y+1),(x,y-1),(x+2,y+1),(x+2,y+4)],fill=shade(ripe,.85))
            for yy in [y+1,y+4,y+7]:d.line((x-1,yy,x,yy+2,x+1,yy),fill=shade(ripe,1.39))
    elif any(s in id for s in ['corn','rice','wheat','barley','millet','grain','sunspike']):
        # Narrow grass blades and grain/maize seedheads; gaps between stalks.
        for j,x in enumerate([9,16,23][:age+1]):
            y=top+[4,0,5][j];stem([(x,31),(x,y+3)],2)
            d.polygon([(x,30),(x-5,24),(x-4,19),(x-1,25)],fill=shade(green,.91))
            d.line((x-4,21,x-1,28),fill=shade(green,1.36))
            if age>1:
                for yy in range(y,y+8,3):
                    d.rectangle((x-2,yy,x+1,yy+2),fill=shade(ripe,.74));d.line((x-1,yy,x+1,yy),fill=shade(ripe,1.44))
            else:d.line((x,y,x+1,y+3),fill=shade(green,1.35))
    elif any(s in id for s in ['cabbage','lettuce','broccoli','artichoke']):
        # A wide cabbage/lettuce rosette or raised broccoli/artichoke head.
        r=[3,5,8,11][age];cy=30-r
        for x,y,w,hh in [(16-r//2,cy+2,r//2+1,r//2),(16+r//2,cy+2,r//2+1,r//2),(16,cy-2,r//2+1,r//2+1)]:broad(x,y,w,hh)
        if age>1:
            if 'broccoli' in id:
                stem([(16,30),(16,cy)],3)
                for x,y in [(11,cy-2),(16,cy-4),(21,cy-2)]:native_bud(d,x,y,ripe,3)
            elif 'artichoke' in id:
                native_bud(d,16,cy-3,ripe,4)
                for x,y in [(13,cy-3),(16,cy-5),(19,cy-3)]:d.line((x,y,x+1,y+2),fill=shade(green,1.24))
            else:broad(16,cy-2,r//2,r//2)
    else:
        # Branching pepper/okra/tomato bush: broad blades and exposed fruit.
        stem([(16,31),(16,top+4)],2)
        branches=[(8,top+8),(24,top+9),(12,top+3),(21,top+2)][:age+1]
        for j,(x,y) in enumerate(branches):
            stem([(16,min(29,y+6)),(x,y)],2);broad(x,y,2+age//2,2)
        if age>1:
            elongated=any(s in id for s in ['chili','okra','aubergine','cucumber'])
            for x,y in [(8,top+13),(23,top+14)] if age==3 else [(23,top+14)]:
                if elongated:y=min(21,y) # full pendant fruit remains inside the 32px tile
                d.line((x,y-3,x,y),fill=shade(green,.82));native_bud(d,x,y,ripe,2,'chili' if elongated else 'round')
    return im

def vines(c,accent,berries,kelp=False,tip=False):
    im=blank();d=ImageDraw.Draw(im)
    points=[(15,0),(13,7),(18,15),(14,24),(16,31)] if not kelp else [(17,0),(14,8),(18,18),(15,31)]
    d.line(points,fill=shade((71,75,87) if not kelp else c,.47),width=3)
    d.line([(x-1,y) for x,y in points],fill=shade(c,1.08))
    for j,(x,y) in enumerate([(14,8),(18,16),(14,25)]):
        native_leaf(d,x,y,7 if kelp else 5,c,j%2==0)
        if berries:native_bud(d,x+(-6 if j%2==0 else 6),y+4,accent,2)
    if tip:native_leaf(d,16,31,4,c,True)
    return im

def mushroom(c,accent):
    im=blank();d=ImageDraw.Draw(im)
    d.polygon([(13,16),(20,16),(20,27),(24,29),(21,31),(10,30),(12,27)],fill=shade(c,.59))
    d.line([(15,17),(15,26),(12,29)],fill=shade(c,1.32),width=2)
    d.polygon([(3,15),(6,8),(12,5),(21,5),(27,11),(29,17),(24,20),(7,20)],fill=shade(accent,.4))
    d.polygon([(4,14),(8,8),(13,6),(21,7),(26,12),(27,16),(7,17)],fill=shade(accent,.95))
    d.line([(7,12),(11,7),(18,6)],fill=shade(accent,1.45),width=2)
    for x,y in [(12,10),(21,11),(18,15)]:crystal(d,x,y,accent,1)
    d.line((8,18,23,18),fill=shade(c,.8));return im

def animate(key, frame, category):
    dst=TEXTURES/(key+'.png');meta=dst.with_suffix('.png.mcmeta')
    if not meta.exists():return save(key,frame,category)
    info=json.loads(meta.read_text()).get('animation',{});old=Image.open(dst)
    fw=info.get('width',old.width);fh=info.get('height',fw)
    count=old.height//fh
    sheet=blank((32,32*count))
    # Keep animation indexes/timing. Animate only small selected bright accents,
    # never jitter the plant silhouette or resample the old frame.
    for n in range(count):
        current=frame.copy()
        for y in range(32):
            for x in range(32):
                pix=current.getpixel((x,y))
                if pix[3] and min(pix[:3])>140 and max(pix[:3])>220:
                    current.putpixel((x,y),shade(pix[:3],[.87,1,1.09,1][n%4])[:3]+(pix[3],))
        sheet.paste(current,(0,n*32))
    # All existing implicit square animations continue to be 32px square.
    if 'width' in info or 'height' in info:
        info['width']=32;info['height']=32;obj=json.loads(meta.read_text());obj['animation']=info
        meta.write_text(json.dumps(obj,indent=2)+'\n')
    return save(key,sheet,category,{'frame_count':count,'frame_size':32,'timing_preserved':True})

def main():
    # Stable existing material palettes; violet/cyan inlays tie equipment together.
    for name,cfg in S.items():
        c=colour(M[name]['pal'][3]);accent=(187,111,239)
        for kind in ['sword','pickaxe','axe','shovel','hoe','helmet','chestplate','leggings','boots']:
            save('item/'+name+'_'+kind,equipment(c,accent,kind,cfg),'equipment')
        geo_path=RES/('assets/zerog_tweaks/geo/item/armor/'+name+'.geo.json')
        oldpath=TEXTURES/('item/armor/'+name+'.png')
        glowpath=TEXTURES/('item/armor/'+name+'_glowmask.png')
        if geo_path.exists() and oldpath.exists():
            original=Image.open(oldpath).convert('RGBA');mask=Image.open(glowpath).convert('RGBA') if glowpath.exists() else None
            im,glow,bounds=atlas(json.loads(geo_path.read_text()),original,c,accent,mask,emit_inlays=name=='olympium')
            save('item/armor/'+name,im,'worn_atlases',{'geo_sha256':digest(geo_path),'face_bounds':bounds,'alpha_preserved':True})
            if name=='olympium':
                assert glow.getbbox(),'Olympium selective inlay mask must not be empty'
                save('item/armor/'+name+'_glowmask',glow,'worn_glowmasks',{'base_size':list(im.size),'selective_inlays_only':True},allow_new=True)
                sections=[]
                for y in range(im.height):
                    x=0
                    while x<im.width:
                        if not glow.getpixel((x,y))[3]:x+=1;continue
                        start=x
                        while x+1<im.width and glow.getpixel((x+1,y))[3]:x+=1
                        sections.append({'x1':start,'y1':y,'x2':x,'y2':y,'alpha':255});x+=1
                artifact('assets/zerog_tweaks/textures/item/armor/olympium.png.mcmeta',{'texture':{'blur':False,'clamp':False},'glowsections':{'sections':sections}},'geckolib_emission_metadata')
                artifact('assets/zerog_tweaks/textures/item/armor/olympium_glowmask.png.mcmeta',{'texture':{'blur':False,'clamp':False}},'geckolib_emission_metadata')
            elif mask:save('item/armor/'+name+'_glowmask',glow,'worn_glowmasks')
        # Vanilla normalized UV contract, with newly painted HD native plate faces.
        for layer in [1,2]:
            path=TEXTURES/f'models/armor/{name}_layer_{layer}.png'
            if not path.exists():continue
            coverage=json.loads((BASE/'vanilla-netherite-uv-coverage.json').read_text())['layers'][str(layer)]
            im,bounds=worn_facets(coverage,c,accent,layer)
            assert im.getchannel('A').resize((64,32),Image.Resampling.NEAREST).tobytes()==bytes(255 if x in coverage['rows'][y] else 0 for y in range(32) for x in range(64)),'Netherite normalized UV coverage mismatch'
            save(f'models/armor/{name}_layer_{layer}',im,'vanilla_armor_uvs',{'face_bounds':bounds,'native_density':2,'vanilla_netherite_alpha':True,'reference_sha256':coverage['source_sha256'],'geometry':'vanilla HumanoidArmorModel; normalized UV coverage unchanged','artwork':'native faceted plates, mirrored chest chevron, recessed cyan/violet inlays'})
    trim_icons()
    bees=functions(DOCS/'zero-g-tweaks-bundle/generators/planet_bees.py',['connected_comb'],['STYLES','FAMILIES'])
    for key,style in bees['FAMILIES'].items():
        _,secondary,accent=bees['STYLES'][style]
        save('item/'+key+'_honeycomb',bees['connected_comb'](accent,secondary),'connected_honeycombs',{'native_size':32,'connected_wax_rims':True,'seven_recessed_cells':True,'ids_unchanged':True})
    save('item/3d/moonsteel_tools',tool_swatch_atlas(),'wielded_tool_atlas',{'size':64,'swatch_size':16,'geometry_and_display_unchanged':True})
    mineral=functions(DOCS/'art-rollout-v3/generate.py',['tint','blank','mineral'])
    woods=functions(DOCS/'wood-dust-art-v2/generate.py',['ramp','bark','rings','boards','leaves','dust'],['WOODS'])
    mineral['tint']=shade;woods['ramp']=shade
    materials={k:colour(v['pal'][3]) for k,v in M.items()}
    materials.update({r['id']:colour(r['colour']) for r in json.loads((args.code/'tools/planet_material_art_manifest.json').read_text())})
    for path in sorted((TEXTURES/'item').glob('*.png')):
        id=path.stem;name=id.removeprefix('raw_').removesuffix('_raw')
        name=re.sub(r'_(ingot|nugget|dust|gem)$','',name)
        c=materials.get(id,materials.get(name))
        if c is None:continue
        if id.endswith('_ingot'):save('item/'+id,metal_bar(c,(189,114,244)),'ingots')
        elif id.startswith('raw_') or id.endswith('_raw'):save('item/'+id,raw_chunk(c,(182,110,240)),'raw_materials')
        elif id.endswith('dust') or M.get(id,{}).get('role')=='dust':save('item/'+id,woods['dust'](c,id),'dusts')
        elif id.endswith('_nugget'):save('item/'+id,mineral['mineral'](c,'nugget',(176,106,237)),'nuggets')
        elif M.get(id,{}).get('role')=='fuel':save('item/'+id,fuel_chunk(c,colour(M[id]['pal'][5])),'fuels')
    for i,(name,pal) in enumerate(woods['WOODS'].items()):
        for key,im in [(name+'_log',woods['bark'](pal['bark'],100+i)),(name+'_log_top',woods['rings'](pal['wood'],pal['bark'],False)),
            ('stripped_'+name+'_log',woods['bark'](pal['wood'],200+i,True)),('stripped_'+name+'_log_top',woods['rings'](pal['wood'],pal['bark'],True)),
            (name+'_planks',woods['boards'](pal['wood'],300+i)),(name+'_leaves',woods['leaves'](pal['leaf'],pal['bud'],400+i))]:save('block/'+key,im,'wood_leaves')
        save('block/'+name+'_door_top',wooden_door(pal['wood'],True),'wood_joinery')
        save('block/'+name+'_door_bottom',wooden_door(pal['wood'],False),'wood_joinery')
        item=blank();di=ImageDraw.Draw(item)
        di.rectangle((7,2,24,29),fill=shade(pal['wood'],.54))
        di.rectangle((8,3,22,28),fill=shade(pal['wood'],1.0))
        for x in [10,16,21]:di.line((x,4,x,28),fill=shade(pal['wood'],.7));di.line((x+1,4,x+1,27),fill=shade(pal['wood'],1.29))
        for x in [11,18]:di.rectangle((x,7,x+3,14),fill=(0,0,0,0))
        di.line((9,18,21,18),fill=shade(pal['wood'],1.4));di.rectangle((20,20,21,22),fill=shade((151,177,191),1.17))
        save('item/'+name+'_door',item,'wood_joinery_items')
    botany=functions(DOCS/'planet-botany-v2/generate.py',['rgb','palette','shade','leaf','bud','flower','shrub','crop','fruiticon'],['themes','leaves','fruits','catalog','oldgroups','gourds'])
    botany['leaf']=native_leaf;botany['bud']=native_bud;botany['crop']=native_crop;botany['rgb']=shade
    for theme,spec in botany['catalog'].items():
        for i,id in enumerate(spec['flowers']):save('block/'+id,botany['flower'](theme,i,id),'flowers')
        for i,id in enumerate(spec['shrubs']):save('block/'+id,botany['shrub'](theme,i),'shrubs')
        for id in spec['fruits']+[spec['crop']]+botany['oldgroups'][theme]:
            save('item/'+id,botany['fruiticon'](theme,id),'harvested_food')
            save('item/'+id+'_seeds',botany['fruiticon'](theme,id,True),'seeds')
            for age in range(4):
                for suffix in ['_stage','_crop_stage']:save('block/'+id+suffix+str(age),botany['crop'](theme,id,age),'crop_stages')
    terrain=functions(DOCS/'zero-g-tweaks-bundle/generators/planet_art_refresh.py',['tint','grass_colour','vegetation','flower','seeds','grain'])
    terrain['tint']=lambda c,k=1:shade(c,k)[:3]
    terrain['grass_colour']=lambda c:c
    dimthemes=json.loads((args.code/'tools/planet_materials.json').read_text())['dimension_themes']
    dims=set(dimthemes)
    for dim,theme in dimthemes.items():
        green,accent=botany['palette'](theme);seed=int(hashlib.sha256(dim.encode()).hexdigest()[:8],16)
        for id in ['_cave_vines','_cave_vines_plant','_cave_vines_berries','_cave_vines_plant_berries']:
            save('block/'+dim+id,vines(green,accent,'berries' in id,tip=id=='_cave_vines'),'cave_vines')
        for kind in ['short','tall']:
            im=terrain['vegetation'](green,seed,kind)
            if kind=='tall':save('block/'+dim+'_tall_grass',im.crop((0,32,32,64)),'grasses');save('block/'+dim+'_tall_grass_top',im.crop((0,0,32,32)),'grasses')
            else:save('block/'+dim+'_short_grass',im,'grasses')
        animate('block/'+dim+'_glow_mushroom',mushroom(green,accent),'mushrooms')
        animate('block/'+dim+'_glow_flower',botany['flower'](theme,seed,dim+'_torchflower'),'planetary_flowers')
        animate('block/'+dim+'_glow_shrub',botany['shrub'](theme,seed),'planetary_shrubs')
    for key in ['glowkelp','glowkelp_plant']:animate('block/'+key,vines((78,170,158),(183,125,240),True,kelp=True),'ocean_vegetation')
    save('item/glowkelp',vines((78,170,158),(183,125,240),True,kelp=True),'ocean_vegetation_items')
    for key in ['pyrevine','pyrevine_lit','pyrevine_plant','pyrevine_plant_lit']:animate('block/'+key,vines((94,141,116),(240,156,83),'lit' in key),'climbing_vines')
    for theme in ['moon','mars','cerulon','skarn','eidolon','solvane']:
        green,accent=botany['palette'](theme)
        for suffix in ['ivy','glow_ivy','venom_ivy','fruit_ivy','fruit_ivy_ripe']:
            save('block/'+theme+'_'+suffix,vines(green,accent,suffix in ['fruit_ivy_ripe','glow_ivy','venom_ivy']),'wall_vines')
    for id,theme in [('starbloom','cerulon'),('ghostbloom','eidolon'),('frostfern','eidolon'),('emberthorn','skarn'),('cinder_cap','skarn')]:
        green,accent=botany['palette'](theme)
        im=mushroom(green,accent) if 'cap' in id else botany['shrub'](theme,4) if id in ['frostfern','emberthorn'] else botany['flower'](theme,1,id)
        animate('block/'+id,im,'legacy_plants')
    for id,theme in [('rust_tuber','mars'),('skyberry_bush','cerulon')]:
        for age in range(4):save('block/'+id+('_crop_stage' if id=='rust_tuber' else '_stage')+str(age),botany['crop'](theme,'rust_beet' if id=='rust_tuber' else 'solar_tomato',age),'legacy_crop_stages')
    for id,theme in [('moon_millet','moon'),('rustgrain','mars'),('azure_rice','cerulon'),('ember_wheat','skarn'),('frost_barley','eidolon'),('sunspike','solvane')]:
        for age in range(4):save('block/'+id+'_crop_stage'+str(age),native_crop(theme,id,age),'grain_crop_stages')
    for id,theme in botany['gourds'].items():
        save('block/'+id+'_stem',native_crop(theme,id,3),'gourd_ground_vines')
        attached=native_crop(theme,id,3);ad=ImageDraw.Draw(attached)
        ad.line([(16,29),(24,29),(31,27)],fill=shade(botany['palette'](theme)[0],.76),width=2)
        save('block/'+id+'_attached_stem',attached,'gourd_ground_vines')
    for id,theme in [('shardwood','cerulon'),('charwood','skarn'),('hoarwood','eidolon'),('gildwood','solvane')]:
        save('block/'+id+'_sapling',botany['shrub'](theme,2),'saplings')
    for key in ['solflower','solflower_crop_stage0','solflower_crop_stage1','solflower_crop_stage2','solflower_crop_stage3']:
        age=int(key[-1]) if key[-1].isdigit() else 3;save('block/'+key,botany['crop']('solvane','corona_corn',age) if 'stage' in key else botany['flower']('solvane',0,'sun_crown'),'legacy_plants')
    for id in ['recall_anchor','group_anchor']:
        save('item/'+id,anchor(id=='group_anchor'),'new_gate_items',allow_new=True)
        artifact('assets/zerog_tweaks/models/item/'+id+'.json',{'parent':'minecraft:item/generated','textures':{'layer0':'zerog_tweaks:item/'+id}},'gate_item_models')
    transport()
    planetary_kelp()
    validate_and_report()

def validate_and_report():
    errors=[]
    for row in ROWS:
        src=BASE/'source'/row['path'];im=Image.open(src)
        if not im.getbbox():errors.append('Empty '+row['path'])
        for relative in row['layers']:
            if digest(RES/relative)!=row['sha256']:errors.append('Layer mismatch '+relative)
        meta=src.with_suffix('.png.mcmeta')
        if meta.exists() and 'animation' in json.loads(meta.read_text()):
            animation=json.loads(meta.read_text()).get('animation',{})
            fw=animation.get('width',im.width);fh=animation.get('height',fw)
            if im.width%fw or im.height%fh:errors.append('Frame mismatch '+row['path'])
            count=im.width//fw*im.height//fh
            for frame in animation.get('frames',[]):
                n=frame.get('index') if isinstance(frame,dict) else frame
                if not 0<=n<count:errors.append('Invalid animation index '+row['path'])
    for row in MODEL_ROWS:
        src=BASE/'source'/row['path'];obj=json.loads(src.read_text())
        if digest(RES/row['path'])!=row['sha256']:errors.append('JSON source mismatch '+row['path'])
        for value in obj.get('textures',{}).values():
            if value.startswith('zerog_tweaks:'):
                relative='assets/zerog_tweaks/textures/'+value.split(':',1)[1]+'.png'
                if not (RES/relative).exists():errors.append('Missing model texture '+relative)
        for cube in obj.get('elements',[]):
            for face in cube.get('faces',{}).values():
                if any(not 0<=v<=16 for v in face.get('uv',[])):errors.append('Invalid Java UV '+row['path'])
    rows={r['path']:r for r in ROWS};counts=Counter(r['category'] for r in rows.values())
    untouched=[p.relative_to(RES).as_posix() for p in TEXTURES.rglob('*.png') if p.relative_to(RES).as_posix() not in rows]
    original=baseline()
    for r in rows.values():
        r['previous_sha256']=original['textures'].get(r['path'])
        r['baseline_sha256']=r['previous_sha256']
    baseline_changed=sum(r['baseline_sha256']!=r['sha256'] for r in rows.values())
    manifest={'generator':'docs/full-art-rollout-v4/generate.py','source_type':'native pixel drawing, no concept extraction or recolour filter',
              'approved_reference':['docs/art-direction/zerog_equipment_art_reference.png','docs/genetics-runtime-v1/approved-equipment-vegetation-concept.png'],
              'style':'C equipment/materials, A natural volume + C selective botanical buds',
              'license':'All Rights Reserved (new original work); existing repository transport generator provenance retained','category_counts':dict(counts),'changed_bytes_count':baseline_changed,'baseline_changed_count':baseline_changed,'baseline_commit':original['commit'],'rerun_changed_count':sum(r.get('rerun_previous_sha256')!=r['sha256'] for r in rows.values()),'canonical_ramps':RAMPS,'ramp_source_ref':'Design 844a6d44 docs/art-direction/generator/style_kit.py','files':list(rows.values()),'models':MODEL_ROWS,'reused_native_sources':REUSED,
              'unchanged_texture_inventory':untouched,'validation_errors':errors,'gpu_verified':False,
              'unchanged_scope':'Geometry, display transforms, registries, fluids, GUI semantics, mobs, worn trim patterns, soil/farmland and machine fronts retained; not claimed reauthored. Item trim overlays match new 32px silhouettes.'}
    (BASE/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    project_rows=[]
    # Editable two-sided native sprite sheets; these are texture source projects,
    # not substitutes for the unchanged 3D handheld/worn model geometry.
    for row in rows.values():
        key=row['path'].split('/textures/')[1].removesuffix('.png')
        if not key.startswith('item/') or '/' in key.removeprefix('item/') or row['size']!=[32,32]:continue
        src=BASE/'source'/row['path'];id=Path(key).name
        element_id=str(uuid.uuid5(uuid.NAMESPACE_URL,'zerog-v4/'+id))
        obj={'meta':{'format_version':'4.10','model_format':'java_block','box_uv':False},
             'name':id+'_sprite_source','resolution':{'width':32,'height':32},
             'elements':[{'name':id,'type':'cube','uuid':element_id,'from':[0,0,8],'to':[16,16,8],
                          'origin':[8,8,8],'box_uv':False,'faces':{'north':{'uv':[0,0,32,32],'texture':0},'south':{'uv':[32,0,0,32],'texture':0}}}],
             'outliner':[element_id],'textures':[{'name':id+'.png','id':'0','uuid':str(uuid.uuid5(uuid.NAMESPACE_URL,'zerog-v4/'+id+'/texture')),
                 'width':32,'height':32,'uv_width':32,'uv_height':32,
                 'source':'data:image/png;base64,'+base64.b64encode(src.read_bytes()).decode()}]}
        path=BASE/'blockbench'/f'{id}.bbmodel';path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(obj,indent=2)+'\n')
        project_rows.append({'path':path.relative_to(DOCS.parent).as_posix(),'sha256':digest(path)})
    (BASE/'blockbench-sprite-source-manifest.json').write_text(json.dumps({'scope':'editable two-face texture sources, not worn/wielded geometry replacements','files':project_rows},indent=2)+'\n')
    # Paginated proof, real PNG pixels at inventory size and enlarged, not concepts.
    categories={'equipment':['equipment','ingots','raw_materials','dusts','new_gate_items','connected_honeycombs'],
                'environment':['flowers','shrubs','crop_stages','grain_crop_stages','gourd_ground_vines','harvested_food','wood_leaves','grasses','cave_vines','ocean_vegetation','mushrooms','wall_vines','legacy_plants','legacy_crop_stages','saplings','planetary_kelp','planetary_kelp_items'],
                'transport':['transport_contract_assets'], 'trim':['native_trim_overlays'],
                'honeycombs':['connected_honeycombs'], 'worn':['vanilla_armor_uvs']}
    tilelookup={k:im for k,im in TILES}
    fonts=[Path('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'),Path('C:/Windows/Fonts/consola.ttf')]
    available=next((f for f in fonts if f.exists()),None)
    font=ImageFont.truetype(str(available),10) if available else ImageFont.load_default()
    for group,cats in categories.items():
        selected=[r for r in rows.values() if r['category'] in cats]
        for page in range(math.ceil(len(selected)/72)):
            batch=selected[page*72:(page+1)*72];sheet=Image.new('RGB',(1008,48+math.ceil(len(batch)/8)*138),(19,25,37));d=ImageDraw.Draw(sheet)
            d.text((12,12),f'Native PNG inspection — {group} {page+1}; no client approval claimed',font=font,fill=(227,233,244))
            for i,r in enumerate(batch):
                key=r['path'].split('/textures/')[1].removesuffix('.png');im=tilelookup[key]
                x=(i%8)*126;y=48+(i//8)*138
                native=im;large=im.resize((round(im.width*80/max(im.size)),round(im.height*80/max(im.size))),Image.Resampling.NEAREST)
                sheet.paste(native,(x+4,y+44),native);sheet.paste(large,(x+40,y),large)
                label=Path(key).name
                d.text((x+4,y+87),label[:21],font=font,fill=(204,223,235));d.text((x+4,y+101),label[21:42],font=font,fill=(204,223,235))
            sheet.save(BASE/f'{group}-native-{page+1:02d}.png')
    # Exact exported front UVs on a schematic humanoid, not a game screenshot.
    # This avoids illegible small atlas thumbnails when reviewing plate details.
    sheet=Image.new('RGB',(1008,510),(19,25,37));d=ImageDraw.Draw(sheet)
    d.text((18,14),'Actual worn textures — front UV fitting study (not in-game approval)',font=font,fill=(227,233,244))
    for col,name in enumerate(['moonsteel','ferrox','nullifite']):
        outer=Image.open(TEXTURES/f'models/armor/{name}_layer_1.png').convert('RGBA')
        inner=Image.open(TEXTURES/f'models/armor/{name}_layer_2.png').convert('RGBA')
        figure=Image.new('RGBA',(32,64));fd=ImageDraw.Draw(figure)
        fd.rectangle((8,0,23,15),fill=(167,139,125,255))
        fd.rectangle((8,16,23,39),fill=(53,66,82,255))
        fd.rectangle((0,16,7,39),fill=(167,139,125,255));fd.rectangle((24,16,31,39),fill=(167,139,125,255))
        fd.rectangle((8,40,23,63),fill=(53,66,82,255))
        fd.rectangle((11,6,12,7),fill=(220,226,231,255));fd.rectangle((19,6,20,7),fill=(220,226,231,255))
        fd.rectangle((14,11,17,11),fill=(94,72,66,255))
        for tex,box,pos in [(outer,(16,16,32,32),(8,0)),(outer,(40,40,56,64),(8,16)),
                            (outer,(88,40,96,64),(0,16)),(outer,(88,40,96,64),(24,16)),
                            (inner,(8,40,16,64),(8,40)),(inner,(8,40,16,64),(16,40)),
                            (outer,(8,40,16,64),(8,40)),(outer,(8,40,16,64),(16,40))]:
            face=tex.crop(box)
            if pos in [(24,16),(16,40)]:face=face.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
            figure.alpha_composite(face,pos)
        figure=figure.resize((192,384),Image.Resampling.NEAREST)
        sheet.paste(figure,(col*336+72,58),figure)
        d.text((col*336+72,460),name+' / native 128x64 layers',font=font,fill=(204,223,235))
    sheet.save(BASE/'worn-front-fit-preview.png')
    if errors:raise SystemExit('\n'.join(errors))
    print(json.dumps({'unique_textures':len(rows),'category_counts':dict(counts),'unchanged':len(untouched),'validation_errors':errors}))

if __name__=='__main__':main()
